/*                          _       _
 *__      _____  __ ___   ___  __ _| |_ ___
 *\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
 * \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
 *  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
 *
 * Copyright © 2016 - 2018 Weaviate. All rights reserved.
 * LICENSE: https://github.com/creativesoftwarefdn/weaviate/blob/develop/LICENSE.md
 * AUTHOR: Bob van Luijt (bob@kub.design)
 * See www.creativesoftwarefdn.org for details
 * Contact: @CreativeSofwFdn / bob@kub.design
 */
// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWeaviateActionHistoryGetParams creates a new WeaviateActionHistoryGetParams object
// no default values defined in spec.
func NewWeaviateActionHistoryGetParams() WeaviateActionHistoryGetParams {

	return WeaviateActionHistoryGetParams{}
}

// WeaviateActionHistoryGetParams contains all the bound params for the weaviate action history get operation
// typically these are obtained from a http.Request
//
// swagger:parameters weaviate.action.history.get
type WeaviateActionHistoryGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Unique ID of the action.
	  Required: true
	  In: path
	*/
	ActionID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewWeaviateActionHistoryGetParams() beforehand.
func (o *WeaviateActionHistoryGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rActionID, rhkActionID, _ := route.Params.GetOK("actionId")
	if err := o.bindActionID(rActionID, rhkActionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindActionID binds and validates parameter ActionID from path.
func (o *WeaviateActionHistoryGetParams) bindActionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("actionId", "path", "strfmt.UUID", raw)
	}
	o.ActionID = *(value.(*strfmt.UUID))

	if err := o.validateActionID(formats); err != nil {
		return err
	}

	return nil
}

// validateActionID carries on validations for parameter ActionID
func (o *WeaviateActionHistoryGetParams) validateActionID(formats strfmt.Registry) error {

	if err := validate.FormatOf("actionId", "path", "uuid", o.ActionID.String(), formats); err != nil {
		return err
	}
	return nil
}
