/*                          _       _
 *__      _____  __ ___   ___  __ _| |_ ___
 *\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
 * \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
 *  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
 *
 * Copyright © 2016 - 2019 Weaviate. All rights reserved.
 * LICENSE: https://github.com/creativesoftwarefdn/weaviate/blob/develop/LICENSE.md
 * DESIGN & CONCEPT: Bob van Luijt (@bobvanluijt)
 * CONTACT: hello@creativesoftwarefdn.org
 */ // Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/creativesoftwarefdn/weaviate/models"
)

// WeaviateActionsReferencesDeleteNoContentCode is the HTTP code returned for type WeaviateActionsReferencesDeleteNoContent
const WeaviateActionsReferencesDeleteNoContentCode int = 204

/*WeaviateActionsReferencesDeleteNoContent Successfully deleted.

swagger:response weaviateActionsReferencesDeleteNoContent
*/
type WeaviateActionsReferencesDeleteNoContent struct {
}

// NewWeaviateActionsReferencesDeleteNoContent creates WeaviateActionsReferencesDeleteNoContent with default headers values
func NewWeaviateActionsReferencesDeleteNoContent() *WeaviateActionsReferencesDeleteNoContent {

	return &WeaviateActionsReferencesDeleteNoContent{}
}

// WriteResponse to the client
func (o *WeaviateActionsReferencesDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// WeaviateActionsReferencesDeleteUnauthorizedCode is the HTTP code returned for type WeaviateActionsReferencesDeleteUnauthorized
const WeaviateActionsReferencesDeleteUnauthorizedCode int = 401

/*WeaviateActionsReferencesDeleteUnauthorized Unauthorized or invalid credentials.

swagger:response weaviateActionsReferencesDeleteUnauthorized
*/
type WeaviateActionsReferencesDeleteUnauthorized struct {
}

// NewWeaviateActionsReferencesDeleteUnauthorized creates WeaviateActionsReferencesDeleteUnauthorized with default headers values
func NewWeaviateActionsReferencesDeleteUnauthorized() *WeaviateActionsReferencesDeleteUnauthorized {

	return &WeaviateActionsReferencesDeleteUnauthorized{}
}

// WriteResponse to the client
func (o *WeaviateActionsReferencesDeleteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// WeaviateActionsReferencesDeleteForbiddenCode is the HTTP code returned for type WeaviateActionsReferencesDeleteForbidden
const WeaviateActionsReferencesDeleteForbiddenCode int = 403

/*WeaviateActionsReferencesDeleteForbidden Insufficient permissions.

swagger:response weaviateActionsReferencesDeleteForbidden
*/
type WeaviateActionsReferencesDeleteForbidden struct {
}

// NewWeaviateActionsReferencesDeleteForbidden creates WeaviateActionsReferencesDeleteForbidden with default headers values
func NewWeaviateActionsReferencesDeleteForbidden() *WeaviateActionsReferencesDeleteForbidden {

	return &WeaviateActionsReferencesDeleteForbidden{}
}

// WriteResponse to the client
func (o *WeaviateActionsReferencesDeleteForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// WeaviateActionsReferencesDeleteNotFoundCode is the HTTP code returned for type WeaviateActionsReferencesDeleteNotFound
const WeaviateActionsReferencesDeleteNotFoundCode int = 404

/*WeaviateActionsReferencesDeleteNotFound Successful query result but no resource was found.

swagger:response weaviateActionsReferencesDeleteNotFound
*/
type WeaviateActionsReferencesDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewWeaviateActionsReferencesDeleteNotFound creates WeaviateActionsReferencesDeleteNotFound with default headers values
func NewWeaviateActionsReferencesDeleteNotFound() *WeaviateActionsReferencesDeleteNotFound {

	return &WeaviateActionsReferencesDeleteNotFound{}
}

// WithPayload adds the payload to the weaviate actions references delete not found response
func (o *WeaviateActionsReferencesDeleteNotFound) WithPayload(payload *models.ErrorResponse) *WeaviateActionsReferencesDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the weaviate actions references delete not found response
func (o *WeaviateActionsReferencesDeleteNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WeaviateActionsReferencesDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WeaviateActionsReferencesDeleteInternalServerErrorCode is the HTTP code returned for type WeaviateActionsReferencesDeleteInternalServerError
const WeaviateActionsReferencesDeleteInternalServerErrorCode int = 500

/*WeaviateActionsReferencesDeleteInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response weaviateActionsReferencesDeleteInternalServerError
*/
type WeaviateActionsReferencesDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewWeaviateActionsReferencesDeleteInternalServerError creates WeaviateActionsReferencesDeleteInternalServerError with default headers values
func NewWeaviateActionsReferencesDeleteInternalServerError() *WeaviateActionsReferencesDeleteInternalServerError {

	return &WeaviateActionsReferencesDeleteInternalServerError{}
}

// WithPayload adds the payload to the weaviate actions references delete internal server error response
func (o *WeaviateActionsReferencesDeleteInternalServerError) WithPayload(payload *models.ErrorResponse) *WeaviateActionsReferencesDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the weaviate actions references delete internal server error response
func (o *WeaviateActionsReferencesDeleteInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WeaviateActionsReferencesDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
