// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PeerPing peer ping
// swagger:model PeerPing
type PeerPing struct {

	// (base64 encoded) hash of the current schema
	SchemaHash string `json:"schemaHash,omitempty"`
}

// Validate validates this peer ping
func (m *PeerPing) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerPing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerPing) UnmarshalBinary(b []byte) error {
	var res PeerPing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
