---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8091'
    - --scheme
    - http
    image: gsi/weaviate
    ports:
    - 8091:8091
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
    restart: 'no'
    environment:
      OPENAI_APIKEY: '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'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTOR_INDEX_TYPE: 'hnsw'
      GEMINI_ALLOCATION_ID: '0b391a1a-b916-11ed-afcb-0242ac1c0002'
      GEMINI_DATA_DIRECTORY: '/var/lib/weaviate'
      GEMINI_FVS_SERVER: 'fake_fvs'
      GEMINI_DEBUG: 'false'
      GEMINI_MIN_RECORDS_CHECK: 'false'
  t2v-transformers:
    image: gsi/t2v 
    ports:
     - "8080:8080"
    restart: 'no'
    environment:
      ENABLE_CUDA: 0 
  fake_fvs:
    image: gsi/fake_fvs
    ports:
    - "7761:7761"
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
    restart: 'no'
...
