//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2025 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

package stopwords

const (
	ArabicPreset     = "ar"
	CatalanPreset    = "ca"
	DanishPreset     = "da"
	GermanPreset     = "de"
	EnglishPreset    = "en"
	SpanishPreset    = "es"
	BasquePreset     = "eu"
	PersianPreset    = "fa"
	FinnishPreset    = "fi"
	FrenchPreset     = "fr"
	HindiPreset      = "hi"
	HungarianPreset  = "hu"
	ItalianPreset    = "it"
	JapanesePreset   = "ja"
	DutchPreset      = "nl"
	NorwegianPreset  = "no"
	PolishPreset     = "pl"
	PortuguesePreset = "pt"
	RomanianPreset   = "ro"
	RussianPreset    = "ru"
	SwedishPreset    = "sv"
	ThaiPreset       = "th"
	TurkishPreset    = "tr"
	ChinesePreset    = "zh"
	NoPreset         = "none"
)

var Presets = map[string][]string{
	ArabicPreset: {
		"في", "من", "على", "إلى", "عن", "مع", "أن", "كان", "ما", "لم", "لا", "هو", "هي", "هذا", "هذه", "التي", "الذي",
	},
	CatalanPreset: {
		"a", "amb", "ambdós", "ambdues", "apa", "aquell", "aquella", "aquelles", "aquells", "aquí", "baix",
		"cada", "catorze", "com", "consegueixo", "conseguim", "conseguir", "consigueix", "consigueixen",
		"consigueixes", "correu", "dalt", "cinc", "de", "dels", "des", "després", "dintre", "dos", "durant",
		"el", "els", "em", "en", "encara",
	},
	DanishPreset: {
		"og", "i", "jeg", "det", "at", "en", "den", "til", "er", "som", "på", "de", "med", "han", "af", "for",
		"ikke", "der", "var", "mig", "sig", "men", "et", "har", "om", "vi", "min", "havde", "ham", "hun", "nu",
	},
	GermanPreset: {
		"aber", "alle", "allem", "allen", "aller", "alles", "als", "also", "am", "an", "ander", "andere",
		"anderem", "anderen", "anderer", "anderes", "anderm", "andern", "anderr", "anders", "auch", "auf",
		"aus", "bei", "bin", "bis", "bist", "da", "damit", "dann", "der", "den", "des", "dem", "die", "das",
		"dass", "daß", "derselbe", "derselben", "denselben", "desselben", "demselben", "dieselbe", "dieselben",
		"dasselbe", "dazu", "dein", "deine", "deinem", "deinen", "deiner", "deines", "denn", "derer", "dessen",
		"dich", "dir", "du", "dies", "diese", "diesem", "diesen", "dieser", "dieses", "doch", "dort", "durch",
		"ein", "eine", "einem", "einen", "einer", "eines", "einig", "einige", "einigem", "einigen", "einiger",
		"einiges", "einmal", "er", "ihn", "ihm", "es", "etwas", "euer", "eure", "eurem", "euren", "eurer",
		"eures", "für", "gegen", "gewesen", "hab", "habe", "haben", "hat", "hatte", "hatten", "hier", "hin",
		"hinter", "ich", "mich", "mir", "ihr", "ihre", "ihrem", "ihren", "ihrer", "ihres", "euch", "im", "in",
		"indem", "ins", "ist", "jede", "jedem", "jeden", "jeder", "jedes", "jene", "jenem", "jenen", "jener",
		"jenes", "jetzt", "kann", "kein", "keine", "keinem", "keinen", "keiner", "keines", "können", "könnte",
		"machen", "man", "manche", "manchem", "manchen", "mancher", "manches", "mein", "meine", "meinem",
		"meinen", "meiner", "meines", "mit", "muss", "musste", "nach", "nicht", "nichts", "noch", "nun",
		"nur", "ob", "oder", "ohne", "sehr", "sein", "seine", "seinem", "seinen", "seiner", "seines", "selbst",
		"sich", "sie", "ihnen", "sind", "so", "solche", "solchem", "solchen", "solcher", "solches", "soll",
		"sollte", "sondern", "sonst", "über", "um", "und", "uns", "unsere", "unserem", "unseren", "unser",
		"unseres", "unter", "viel", "vom", "von", "vor", "während", "war", "waren", "warst", "was", "weg",
		"weil", "weiter", "welche", "welchem", "welchen", "welcher", "welches", "wenn", "werde", "werden",
		"wie", "wieder", "will", "wir", "wird", "wirst", "wo", "wollen", "wollte", "würde", "würden", "zu",
		"zum", "zur", "zwar", "zwischen",
	},
	EnglishPreset: {
		"a", "an", "and", "are", "as", "at", "be", "but", "by", "for",
		"if", "in", "into", "is", "it", "no", "not", "of", "on", "or", "such", "that",
		"the", "their", "then", "there", "these", "they", "this", "to", "was", "will",
		"with",
	},
	SpanishPreset: {
		"un", "una", "unas", "unos", "uno", "sobre", "todo", "también", "tras", "otro", "algún", "alguno", "alguna",
		"algunos", "algunas", "ser", "es", "soy", "eres", "somos", "sois", "estoy", "esta", "estamos", "estais", "estan",
		"como", "en", "para", "atras", "porque", "por", "qué", "estado", "estaba", "ante", "antes", "siendo", "ambos",
		"pero", "poder", "puede", "puedo", "podemos", "podeis", "pueden", "fui", "fue", "fuimos", "fueron", "hacer",
		"hago", "hace", "hacemos", "haceis", "hacen", "cada", "fin", "incluso", "primero", "desde", "conseguir",
		"consigo", "consigue", "consigues", "conseguimos", "consiguen", "ir", "voy", "va", "vamos", "vais", "van",
		"vaya", "gueno", "ha", "tener", "tengo", "tiene", "tenemos", "teneis", "tienen", "el", "la", "lo", "las", "los",
		"su", "aqui", "mio", "tuyo", "ellos", "ellas", "nos", "nosotros", "vosotros", "vosotras", "si", "dentro", "solo",
		"solamente", "saber", "sabes", "sabe", "sabemos", "sabeis", "saben", "ultimo", "largo", "bastante", "haces",
		"muchos", "aquellos", "aquellas", "sus", "entonces", "tiempo", "verdad", "verdadero", "verdadera", "cierto",
		"ciertos", "cierta", "ciertas", "intentar", "intento", "intenta", "intentas", "intentamos", "intentais",
		"intentan", "dos", "bajo", "arriba", "encima", "usar", "uso", "usas", "usa", "usamos", "usais", "usan",
		"emplear", "empleo", "empleas", "emplean", "ampleamos", "empleais", "valor", "muy", "era", "eras", "eramos",
		"eran", "modo", "bien", "cual", "cuando", "donde", "mientras", "quien", "con", "entre", "sin", "trabajo",
		"trabajar", "trabajas", "trabaja", "trabajamos", "trabajais", "trabajan", "podria", "podrias", "podriamos",
		"podrian", "podriais", "yo", "aquel",
	},
	BasquePreset: {
		"al", "anitz", "arabera", "asko", "baina", "bat", "batzuk", "berez", "da", "dago", "dira", "ditu", "dute",
		"edo", "egin", "ere", "eta", "eurak", "ez", "gainera", "gu", "gutxi", "guzti", "haiei", "haiek", "haietan",
		"hainbeste", "hala", "han", "handik", "hango", "hara", "hari", "hark", "hartan", "hau", "hauei", "hauek",
		"hauetan", "hemen", "hemendik", "honela", "honetan", "honengatik", "hor", "hori", "horiek", "horietan",
		"horrela", "horretan", "horrez", "i", "izan", "izango", "bada", "baldin", "bait", "baita", "baizik", "barik",
		"barruan", "besterik", "bezala", "behar", "bilatu", "bitartean", "baino", "ber", "bera", "berau", "beraiek",
		"berriz", "bertan", "bide",
	},
	PersianPreset: {
		"از", "است", "با", "بر", "برای", "به", "بود", "تا", "را", "که", "کند", "ها", "های", "هم", "و", "یک", "می",
		"میشود", "شد", "نیز", "این", "آن", "او", "در", "اما", "اگر", "یا", "شدن", "بودن", "کردن", "توانستن", "گفتن",
		"آمدن", "رفتن", "خواستن", "داشتن", "نزد", "روی", "درباره", "باید", "شاید", "چون",
	},
	FinnishPreset: {
		"olla", "olen", "olet", "on", "olemme", "olette", "ovat", "ole", "oli", "olisi", "olit", "olin", "olimme",
		"olitte", "olivat", "eikä", "eivät", "emme", "en", "et", "ette", "että", "he", "heidän", "heidät", "heihin",
		"heille", "heillä", "heiltä", "heissä", "heistä", "heitä", "hän", "häneen", "hänelle", "hänellä", "häneltä",
		"hänessä", "hänestä", "hänet", "häntä", "itse", "ja", "jolla", "jolle", "jolta", "jossa", "josta", "jota",
		"joka", "jos", "koska", "kuin", "kuka", "kun", "me", "meidän", "meidät", "meihin", "meille", "meillä",
		"meiltä", "meissä", "meistä", "meitä", "miksi", "mikä", "mille", "millä", "miltä", "missä", "mistä", "mitä",
		"myös", "ne", "niiden", "niitä", "niihin", "niille", "niillä", "niiltä", "niissä", "niistä", "nämä", "noiden",
		"noita", "noihin", "noille", "noilla", "noilta", "noissa", "noista", "nuo", "nyt", "siinä", "siitä", "siihen",
		"sillä", "sinä", "sinun", "sinut", "sinuun", "sinulle", "sinulla", "sinulta", "sinussa", "sinusta", "sinua",
		"tai", "tämä", "tämän", "tätä", "tähän", "tälle", "tällä", "tältä", "tässä", "tästä", "tuo", "tuon", "tuot",
		"tuohon", "tuolle", "tuolla", "tuolta", "tuossa", "tuosta", "vaan", "vai", "vain", "se",
	},
	FrenchPreset: {
		"au", "aux", "avec", "ce", "ces", "dans", "de", "des", "du", "elle", "en", "et", "eux", "il", "je", "la",
		"le", "leur", "lui", "ma", "mais", "me", "même", "mes", "moi", "mon", "ne", "nos", "notre", "nous", "on",
		"ou", "par", "pas", "pour", "qu", "que", "qui", "sa", "se", "ses", "son", "sur", "ta", "te", "tes", "toi",
		"ton", "tu", "un", "une", "vos", "votre", "vous", "c", "d", "j", "l", "à", "m", "n", "s", "t", "y", "été",
		"étée", "étées", "étés", "étant", "étante", "étants", "étantes", "suis", "es", "est", "sommes", "êtes",
		"sont", "serai", "seras", "sera", "serons", "serez", "seront", "serais", "serait", "serions", "seriez",
		"seraient", "étais", "était", "étions", "étiez", "étaient", "fus", "fut", "fûmes", "fûtes", "furent", "sois",
		"soit", "soyons", "soyez", "soient", "fusse", "fusses", "fût", "fussions", "fussiez", "fussent", "ayant",
		"ayante", "ayantes", "ayants", "eu", "eue", "eues", "eus", "ai", "as", "avons", "avez", "ont", "aurai",
		"auras", "aura", "aurons", "aurez", "auront", "aurais", "aurait", "aurions", "auriez", "auraient", "avais",
		"avait", "avions", "aviez", "avaient", "eut", "eûmes", "eûtes", "eurent", "aie", "aies", "ait", "ayons", "ayez",
		"aient", "eusse", "eusses", "eût", "eussions", "eussiez", "eussent",
	},
	HindiPreset: {
		"अंदर", "अत", "अदि", "अप", "अपना", "अपनि", "अपनी", "अपने", "अभि", "अभी", "आदि", "आप", "इंहिं", "इंहें",
		"इंहों", "इत", "इत्यादि", "इन", "इनका", "इन्हीं", "इन्हें", "इन्हों", "इस", "इसका", "इसकि", "इसकी", "इसके",
		"इसमें", "इसि", "इसी", "इसे", "उंहिं", "उंहें", "उंहों", "उन", "उनका", "उनकि", "उनकी", "उनके", "उनको",
		"उन्हीं", "उन्हें", "उन्हों", "उस", "उसके", "उसि", "उसी", "उसे", "एक", "एवं", "एस", "एसे", "ऐसे", "ओर",
		"और", "कइ", "कई", "कर", "करता", "करते", "करना", "करने", "करें", "कहते", "कहा", "का", "काफि", "काफ़ी",
		"कि", "किंहें", "किंहों", "कितना", "किन्हें", "किन्हों", "किया", "किर", "किस", "किसि", "किसी", "किसे",
		"की", "कुछ", "कुल", "के", "को", "कोइ", "कोई", "कोन", "कोनसा", "कौन", "कौनसा", "गया", "घर", "जब", "जहाँ",
		"जा", "जितना", "जिन", "जिन्हें", "जिन्हों", "जिस", "जिसे", "जीधर", "जेसा", "जेसे", "जैसा", "जैसे", "जो",
		"तक", "तब", "तरह", "तिन", "तिन्हें", "तिन्हों", "तिस", "तिसे", "तो", "था", "थि", "थी", "थे", "दबारा",
		"दवारा", "दिया", "दुसरा", "दुसरे", "दूसरे", "दो", "द्वारा", "न", "नहिं", "नहीं", "ना", "निचे", "निहायत",
		"नीचे", "ने", "पर", "पहले", "पुरा", "पूरा", "पे", "फिर", "बनी", "बहि", "बही", "बहुत", "बाद", "बाला",
		"बिलकुल", "भि", "भी", "भीतर", "मगर", "मानो", "मे", "में", "यदि", "यह", "यहाँ", "यहि", "यही", "या", "यिह",
		"ये", "रखें", "रवासा", "रहा", "रहे", "ऱ्वासा", "लिए", "लिये", "लेकिन", "व", "वगेरह", "वर्गु", "वह", "वहाँ",
		"वहिं", "वहीं", "वाले", "वुह", "वे", "वग़ैरह", "संग", "सकता", "सकते", "सबसे", "सभि", "सभी", "साथ", "साबुत",
		"साभ", "सारा", "से", "सो", "हि", "ही", "हुअ", "हुआ", "हुइ", "हुई", "हुए", "हे", "हें", "है", "हैं", "हो",
		"होता", "होति", "होती", "होते", "होना", "होने",
	},
	HungarianPreset: {
		"a", "ahogy", "ahol", "aki", "akik", "akkor", "alatt", "által", "általában", "amely", "amelyek", "amelyekben",
		"amelyeket", "amelyet", "amelynek", "ami", "amit", "amolyan", "amíg", "amikor", "át", "abban", "ahhoz",
		"annak", "arra", "arról", "az", "azok", "azon", "azt", "azzal", "azért", "aztán", "azután", "azonban", "bár",
		"be", "belül", "benne", "cikk", "cikkek", "cikkeket", "csak", "de", "e", "eddig", "egész", "egy", "egyes",
		"egyetlen", "egyéb", "egyik", "egyre", "ekkor", "el", "elég", "ellen", "elő", "először", "előtt", "első", "én",
		"éppen", "ebben", "ehhez", "emez", "ennek", "erre", "ez", "ezek", "ezen", "ezt", "ezzel", "ezért", "fel",
		"felé", "hanem", "hiszen", "hogy", "hogyan", "igen", "így", "illetve", "ill.", "ill", "ilyen", "ilyenkor",
		"ison", "ismét", "itt", "jó", "jól", "jobban", "kell", "kellene", "keresztül", "keressünk", "ki", "kívül",
		"között", "közül", "legalább", "lehet", "lehetett", "legyen", "lenne", "lenni", "lesz", "lett", "maga",
		"magát", "majd", "majd", "már", "más", "másik", "meg", "még", "mellett", "mert", "mely", "melyek", "mi",
		"mit", "míg", "miért", "milyen", "mikor", "minden", "mindent", "mindenki", "mindig", "mint", "mintha",
		"mivel", "most", "nagy", "nagyobb", "nagyon", "ne", "néha", "nekem", "neki", "nem", "néhány", "nélkül",
		"nincs", "olyan", "ott", "össze", "ő", "ők", "őket", "pedig", "persze", "rá", "s", "saját", "sem", "semmi",
		"sok", "sokat", "sokkal", "számára", "szemben", "szerint", "szinte", "talán", "tehát", "teljes", "tovább",
		"továbbá", "több", "úgy", "ugyanis", "új", "újabb", "újra", "után", "utána", "utolsó", "vagy", "vagyis",
		"valaki", "valami", "valamint", "való", "vagyok", "van", "vannak", "volt", "voltam", "voltak", "voltunk",
		"vissza", "vele", "viszont", "volna",
	},
	ItalianPreset: {
		"ad", "al", "allo", "ai", "agli", "all", "agl", "alla", "alle", "con", "col", "coi", "da", "dal", "dallo",
		"dai", "dagli", "dall", "dagl", "dalla", "dalle", "di", "del", "dello", "dei", "degli", "dell", "degl",
		"della", "delle", "in", "nel", "nello", "nei", "negli", "nell", "negl", "nella", "nelle", "su", "sul",
		"sullo", "sui", "sugli", "sull", "sugl", "sulla", "sulle", "per", "tra", "contro", "io", "tu", "lui",
		"lei", "noi", "voi", "loro", "mio", "mia", "miei", "mie", "tuo", "tua", "tuoi", "tue", "suo", "sua",
		"suoi", "sue", "nostro", "nostra", "nostri", "nostre", "vostro", "vostra", "vostri", "vostre", "mi",
		"ti", "ci", "vi", "lo", "la", "li", "le", "gli", "ne", "il", "un", "uno", "una", "ma", "ed", "se",
		"perché", "anche", "come", "dov", "dove", "che", "chi", "cui", "non", "più", "quale", "quanto", "quanti",
		"quanta", "quante", "quello", "quelli", "quella", "quelle", "questo", "questi", "questa", "queste", "si",
		"tutto", "tutti", "a", "c", "e", "i", "l", "o", "ho", "hai", "ha", "abbiamo", "avete", "hanno", "abbia",
		"abbiate", "abbiano", "avrà", "avrai", "avrò", "avremo", "avrete", "avranno", "avrei", "avresti", "avrebbe",
		"avremmo", "avreste", "avrebbero", "avevo", "avevi", "aveva", "avevamo", "avevate", "avevano", "ebbi",
		"avesti", "ebbe", "avemmo", "aveste", "ebbero", "avessi", "avesse", "avessimo", "avessero", "avendo",
		"avuto", "avuta", "avuti", "avute", "sono", "sei", "è", "siamo", "siete", "sia", "siate", "siano", "sarà",
		"sarai", "sarò", "saremo", "sarete", "saranno", "sarei", "saresti", "sarebbe", "saremmo", "sareste",
		"sarebbero", "ero", "eri", "era", "eravamo", "eravate", "erano", "fui", "fosti", "fu", "fummo", "foste",
		"furono", "fossi", "fosse", "fossimo", "fossero", "essendo", "faccio", "fai", "facciamo", "fanno", "faccia",
		"facciate", "facciano", "farà", "farai", "farò", "faremo", "farete", "faranno", "farei", "faresti", "farebbe",
		"faremmo", "fareste", "farebbero", "facevo", "facevi", "faceva", "facevamo", "facevate", "facevano", "feci",
		"facesti", "fece", "facemmo", "faceste", "fecero", "facessi", "facesse", "facessimo", "facessero", "facendo",
		"sto", "stai", "sta", "stiamo", "stanno", "stia", "stiate", "stiano", "starà", "starai", "starò", "staremo",
		"starete", "staranno", "starei", "staresti", "starebbe", "staremmo", "stareste", "starebbero", "stavo",
		"stavi", "stava", "stavamo", "stavate", "stavano", "stetti", "stesti", "stette", "stemmo", "steste",
		"stettero", "stessi", "stesse", "stessimo", "stessero", "stando",
	},
	JapanesePreset: {
		"の", "に", "は", "を", "た", "が", "で", "て", "と", "し", "れ", "さ", "ある", "いる", "も", "する", "から", "な",
		"こと", "として", "い", "や", "れる", "など", "なっ", "ない", "この", "ため", "その", "あっ", "よう", "また", "もの",
		"という", "あり", "まで", "られ", "なる", "へ", "か", "だ", "これ", "によって", "により", "おり", "より", "による",
		"ず", "なり", "られる", "において", "ば", "なかっ", "なく", "しかし", "について", "せ", "だっ", "その後", "できる",
		"それ", "う", "ので", "なお", "のみ", "でき", "き", "つ", "における", "および", "いう", "さらに", "でも", "ら",
		"たり", "その他", "に関する", "たち", "ます", "ん", "なら", "に対して", "特に", "せる", "及び", "これら", "とき",
		"では", "にて", "ほか", "ながら", "うち", "そして", "とともに", "ただし", "かつて", "それぞれ", "または", "お",
		"ほど", "ものの", "に対する", "ほとんど", "と共に", "といった", "です", "とも", "ところ", "ここ",
	},
	DutchPreset: {
		"de", "en", "van", "ik", "te", "dat", "die", "in", "een", "hij", "het", "niet", "zijn", "is", "was", "op",
		"aan", "met", "als", "voor", "had", "er", "maar", "om", "hem", "dan", "zou", "of", "wat", "mijn", "men",
		"dit", "zo", "door", "over", "ze", "zich", "bij", "ook", "tot", "je", "mij", "uit", "der", "daar", "haar",
		"naar", "heb", "hoe", "heeft", "hebben", "deze", "u", "want", "nog", "zal", "me", "zij", "nu", "ge", "geen",
		"omdat", "iets", "worden", "toch", "al", "waren", "veel", "meer", "doen", "toen", "moet", "ben", "zonder",
		"kan", "hun", "dus", "alles", "onder", "ja", "eens", "hier", "wie", "werd", "altijd", "doch", "wordt",
		"wezen", "kunnen", "ons", "zelf", "tegen", "na", "reeds", "wil", "kon", "niets", "uw", "iemand", "geweest",
		"andere",
	},
	NorwegianPreset: {
		"og", "i", "jeg", "det", "at", "en", "et", "den", "til", "er", "som", "på", "de", "med", "han", "av",
		"ikke", "ikkje", "der", "så", "var", "meg", "seg", "men", "ett", "har", "om", "vi", "min", "mitt",
		"ha", "hadde", "hun", "nå", "over", "da", "ved", "fra", "du", "ut", "sin", "dem", "oss", "opp", "man",
		"kan", "hans", "hvor", "eller", "hva", "skal", "selv", "sjøl", "her", "alle", "vil", "bli", "ble",
		"blei", "blitt", "kunne", "inn", "når", "være", "kom", "noen", "noe", "ville", "dere", "som", "deres",
		"kun", "ja", "etter", "ned", "skulle", "denne", "for", "deg", "si", "sine", "sitt", "mot", "å", "meget",
		"hvorfor", "dette", "disse", "uten", "hvordan", "ingen", "din", "ditt", "blir", "samme", "hvilken",
		"hvilke", "sånn", "inni", "mellom", "vår", "hver", "hvem", "vors", "hvis", "både", "bare", "enn",
		"fordi", "før", "mange", "også", "slik", "vært", "være", "båe", "begge", "siden", "dykk", "dykkar",
		"dei", "deira", "deires", "deim", "di", "då", "eg", "ein", "eit", "eitt", "elles", "honom", "hjå",
		"ho", "hoe", "henne", "hennar", "hennes", "hoss", "hossen", "ingenting", "inkje", "kven", "kvar",
		"kvifor", "me", "medan", "mi", "mine", "mykje", "no", "nokon", "noka", "nokor", "noko", "nokre",
		"si", "sia", "sidan", "so", "somt", "somme", "um", "upp", "vere", "vore", "verte", "vort", "varte",
		"vart",
	},
	PolishPreset: {
		"ach", "aj", "albo", "bardzo", "bez", "bo", "być", "ci", "ciebie", "cię", "co", "czy", "daleko", "dla",
		"dlaczego", "dlatego", "do", "dobrze", "dokąd", "dość", "dużo", "dwa", "dwaj", "dwie", "dwoje", "dziś",
		"dzisiaj", "gdyby", "gdzie", "go", "ich", "ile", "im", "inny", "ja", "ją", "jak", "jakby", "jaki", "je",
		"jeden", "jedna", "jedno", "jego", "jej", "jemu", "jeśli", "jest", "jestem", "jeżeli", "już", "każdy",
		"kiedy", "kierunku", "kto", "ku", "lub", "ma", "mają", "mam", "mi", "mną", "mnie", "moi", "mój", "moja",
		"moje", "może", "mu", "my", "na", "nam", "nami", "nas", "nasi", "nasz", "nasza", "nasze", "natychmiast",
		"nią", "nic", "nich", "nie", "niego", "niej", "niemu", "nigdy", "nim", "nimi", "niż", "obok", "od",
		"około", "on", "ona", "one", "oni", "ono", "owszem", "pan", "po", "pod", "podczas", "pomimo", "ponad",
		"ponieważ", "powinien", "powinna", "powinni", "powinno", "poza", "przed", "przedtem", "przez", "przy",
		"roku", "również", "sam", "sama", "są", "się", "skąd", "sobie", "sobą", "sposób", "swoje", "ta", "tak",
		"taka", "taki", "takie", "także", "tam", "te", "tego", "tej", "temu", "ten", "teraz", "też", "to", "tobą",
		"tobie", "toteż", "trzeba", "tu", "tutaj", "twoi", "twój", "twoja", "twoje", "ty", "wam", "wami", "was",
		"wasi", "wasz", "wasza", "wasze", "we", "więc", "wszystko", "wtedy", "wy", "właśnie", "z", "za", "żaden",
		"zawsze", "że", "żeby",
	},
	PortuguesePreset: {
		"de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "com", "não", "uma", "os", "no", "se", "na",
		"por", "mais", "as", "dos", "como", "mas", "ao", "ele", "das", "à", "seu", "sua", "ou", "quando", "muito",
		"nos", "já", "eu", "também", "só", "pelo", "pela", "até", "isso", "ela", "entre", "depois", "sem", "mesmo",
		"aos", "seus", "quem", "nas", "me", "esse", "eles", "você", "essa", "num", "nem", "suas", "meu", "às",
		"minha", "numa", "pelos", "elas", "qual", "nós", "lhe", "deles", "essas", "esses", "pelas", "este", "dele",
		"tu", "te", "vocês", "vos", "lhes", "meus", "minhas", "teu", "tua", "teus", "tuas", "nosso", "nossa",
		"nossos", "nossas", "dela", "delas", "esta", "estes", "estas", "aquele", "aquela", "aqueles", "aquelas",
		"isto", "aquilo", "estou", "está", "estamos", "estão", "estive", "esteve", "estivemos", "estiveram",
		"estava", "estávamos", "estavam", "estivera", "estivéramos", "esteja", "estejamos", "estejam", "estivesse",
		"estivéssemos", "estivessem", "estiver", "estivermos", "estiverem", "hei", "há", "havemos", "hão", "houve",
		"houvemos", "houveram", "houvera", "houvéramos", "haja", "hajamos", "hajam", "houvesse", "houvéssemos",
		"houvessem", "houver", "houvermos", "houverem", "houverei", "houverá", "houveremos", "houverão",
		"houveria", "houveríamos", "houveriam", "sou", "somos", "são", "era", "éramos", "eram", "fui", "foi",
		"fomos", "foram", "fora", "fôramos", "seja", "sejamos", "sejam", "fosse", "fôssemos", "fossem", "for",
		"formos", "forem", "serei", "será", "seremos", "serão", "seria", "seríamos", "seriam", "tenho", "tem",
		"temos", "têm", "tinha", "tínhamos", "tinham", "tive", "teve", "tivemos", "tiveram", "tivera", "tivéramos",
		"tenha", "tenhamos", "tenham", "tivesse", "tivéssemos", "tivessem", "tiver", "tivermos", "tiverem",
		"terei", "terá", "teremos", "terão", "teria", "teríamos", "teriam",
	},
	RomanianPreset: {
		"acea", "aceasta", "această", "aceea", "acei", "aceia", "acel", "acela", "acele", "acelea", "acest", "acesta",
		"aceste", "acestea", "aceşti", "aceştia", "acolo", "acord", "acum", "ai", "aia", "aibă", "aici", "al", "ăla",
		"ale", "alea", "ălea", "altceva", "altcineva", "am", "ar", "are", "aş", "aşadar", "asemenea", "asta", "ăsta",
		"astăzi", "astea", "ăstea", "asupra", "atare", "atât", "atâta", "atâtea", "atâţia", "b", "ba", "bine", "buc",
		"bună", "c", "ca", "că", "căci", "când", "care", "cărei", "căror", "cărui", "cât", "câte", "câţi", "către",
		"citi", "ce", "cel", "celea", "celor", "ceva", "chiar", "cine", "cineva", "câta", "cite", "cit", "conform",
		"cu", "cum", "d", "da", "dacă", "dat", "dată", "dapoi", "de", "degrabă", "decat", "decât", "deci", "dej", "deja",
		"desi", "despre", "din", "dinaintea", "dintr-", "dintre", "doi", "doilea", "două", "drept", "după", "e", "ea",
		"ei", "el", "ele", "eram", "este", "eşti", "eu", "exact", "eşti", "face", "fără", "fata", "fi", "fiind", "final",
		"fost", "fi", "fiu", "fii", "fie", "g", "h", "i", "ia", "iar", "ieri", "îi", "îl", "îmi", "împotriva", "în",
		"înainte", "înaintea", "încât", "încotro", "între", "întrucât", "îţi", "j", "k", "l", "la", "le", "li", "lor",
		"lui", "m", "mă", "mâine", "mea", "mei", "mele", "mereu", "meu", "mi", "mine", "mult", "multă", "mulţi", "n",
		"ne", "ni", "nici", "niciodată", "nimeni", "nimic", "nicio", "niciun", "noastră", "noastre", "noi", "noştri",
		"nostru", "nu", "numai", "o", "or", "ori", "oricând", "orice", "oricine", "oricum", "p", "pai", "parcă",
		"patru", "pe", "pentru", "peste", "pic", "până", "poate", "pot", "prea", "prima", "primul", "prin", "printr-",
		"puţin", "puţina", "puţină", "r", "rog", "s", "sa", "să", "săi", "sale", "sau", "său", "se", "spate", "spre",
		"sub", "sunt", "suntem", "sunteţi", "t", "ta", "tăi", "tale", "tău", "te", "ţi", "tie", "tine", "toată",
		"toate", "tot", "toţi", "totuşi", "trei", "treia", "treilea", "u", "un", "una", "unde", "undeva", "unei",
		"unele", "uneori", "unii", "unor", "unul", "unui", "v", "vă", "vi", "voastră", "voastre", "voi", "voştri",
		"vostru", "vreo", "vreun", "x", "z", "zece", "zero", "zi", "zice",
	},
	RussianPreset: {
		"и", "в", "во", "не", "что", "он", "на", "я", "с", "со", "как", "а", "то", "все", "она", "так", "его", "но",
		"да", "ты", "к", "у", "же", "вы", "за", "бы", "по", "только", "ее", "мне", "было", "вот", "от", "меня",
		"еще", "нет", "о", "из", "ему", "теперь", "когда", "даже", "ну", "вдруг", "ли", "если", "уже", "или", "ни",
		"быть", "был", "него", "до", "вас", "нибудь", "опять", "уж", "вам", "ведь", "там", "потом", "себя", "ничего",
		"ей", "может", "они", "тут", "где", "есть", "надо", "ней", "для", "мы", "тебя", "их", "чем", "была", "сам",
		"чтоб", "без", "будто", "чего", "раз", "тоже", "себе", "под", "будет", "ж", "тогда", "кто", "этот", "того",
		"потому", "этого", "какой", "совсем", "ним", "здесь", "этом", "один", "почти", "мой", "тем", "чтобы", "нее",
		"сейчас", "были", "куда", "зачем", "всех", "никогда", "можно", "при", "наконец", "два", "об", "другой",
		"хоть", "после", "над", "больше", "тот", "через", "эти", "нас", "про", "всего", "них", "какая", "много",
		"разве", "три", "эту", "моя", "впрочем", "хорошо", "свою", "этой", "перед", "иногда", "лучше", "чуть", "том",
		"нельзя", "такой", "им", "более", "всегда", "конечно", "всю", "между",
	},
	SwedishPreset: {
		"och", "det", "att", "i", "en", "jag", "hon", "som", "han", "på", "den", "med", "var", "sig", "för", "så",
		"till", "är", "men", "ett", "om", "hade", "de", "av", "icke", "mig", "du", "henne", "då", "sin", "nu", "har",
		"inte", "hans", "honom", "skulle", "hennes", "där", "min", "man", "ej", "vid", "kunde", "något", "från",
		"ut", "när", "efter", "upp", "vi", "dem", "vara", "vad", "över", "än", "dig", "kan", "sina", "här", "ha",
		"mot", "alla", "under", "någon", "eller", "allt", "mycket", "sedan", "ju", "denna", "själv", "detta", "åt",
		"utan", "varit", "hur", "ingen", "mitt", "ni", "bli", "blev", "oss", "din", "dessa", "några", "deras", "bli",
		"mina", "samma", "vilken", "er", "sådan", "vår", "blivit", "dess", "inom", "mellan", "sådant", "varför",
		"varje", "vilka", "ditt", "vem", "vilket", "sitta", "sådana", "vart", "dina", "vars", "vårt", "våra", "ert",
		"era", "vilkas",
	},
	ThaiPreset: {
		"ก็", "กู", "มึง", "มัน", "เขา", "เรา", "คุณ", "ฉัน", "ครับ", "ค่ะ", "เออ", "อืม", "อือ", "วะ", "ว่ะ", "เว้ย",
		"เฮ้ย", "สิ", "นะ", "จ๊ะ", "จ้ะ", "ละ", "และ", "หรือ", "แต่", "ถ้า", "หาก", "เพราะ", "เพื่อ", "โดย", "ใน",
		"บน", "ล่าง", "ข้าง", "ที่", "ซึ่ง", "อัน", "จาก", "ถึง", "ของ", "กับ", "แก่", "แด่", "ต่อ", "เมื่อ", "ขณะ",
		"ก่อน", "หลัง", "แล้ว", "จะ", "คง", "อาจ", "ต้อง", "ให้", "ได้", "ไป", "มา", "อยู่", "กิน", "ทำ", "พูด",
		"เห็น", "รู้", "ชอบ", "รัก", "เกลียด", "ดี", "เลว", "มาก", "น้อย", "ใหม่", "เก่า", "ใหญ่", "เล็ก", "สูง",
		"ต่ำ", "ดำ", "ขาว", "เป็น", "คือ", "มี", "ใช่", "ไม่",
	},
	TurkishPreset: {
		"acaba", "ama", "aslında", "az", "bazı", "belki", "biri", "birkaç", "birşey", "biz", "bu", "çok", "çünkü",
		"da", "daha", "de", "defa", "diye", "eğer", "en", "gibi", "hem", "hep", "hepsi", "her", "hiç", "için", "ile",
		"ise", "kez", "ki", "kim", "mı", "mu", "mü", "nasıl", "ne", "neden", "nerde", "nerede", "nereye", "niçin",
		"niye", "o", "sanki", "şey", "siz", "şu", "tüm", "ve", "veya", "ya", "yani",
	},
	ChinesePreset: {
		"的", "一", "不", "在", "人", "有", "是", "为", "以", "于", "上", "他", "而", "后", "之", "来", "及", "了", "因",
		"下", "可", "到", "由", "这", "与", "也", "此", "但", "并", "个", "其", "已", "无", "小", "我", "们", "起", "最",
		"再", "今", "去", "好", "只", "又", "或", "很", "亦", "某", "把", "那", "你", "乃", "它", "吧", "被", "比", "别",
		"趁", "当", "从", "到", "得", "打", "凡", "儿", "尔", "该", "各", "给", "跟", "和", "何", "还", "即", "几", "既",
		"看", "据", "距", "靠", "啦", "了", "另", "么", "每", "们", "嘛", "拿", "哪", "那", "您", "凭", "且", "却", "亲",
		"让", "若", "向", "似", "虽", "随", "同", "所", "她", "哇", "嗡", "往", "哪", "些", "向", "沿", "哟", "用", "于",
		"咱", "则", "怎", "曾", "至", "致", "着", "诸", "自",
	},
	NoPreset: {},
}
