linters:
  disable:
    - errcheck
  enable:
    - misspell
    - bodyclose
    - gofumpt
    - exhaustive
    - govet
    - unused
    - nolintlint
linters-settings:
  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    default-signifies-exhaustive: true
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "S1034"
    - linters:
        - staticcheck
      text: "SA1029:"
    - linters:
        - staticcheck
      text: "SA1015:"
    - linters:
        - staticcheck
      text: "SA5011"
    - linters:
        - govet
      text: "composites"
    - linters:
        - staticcheck
      path: ^adapters/handlers/grpc/v1\/(?:[^\/]+\/)*[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
    - linters:
        - staticcheck
      path: ^test/acceptance/grpc\/[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/prepare_reply.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/parse_search_request.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/batch_parse_request.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/service.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: test/acceptance/grpc/grpc_test_deprecated.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/mapping.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: test/acceptance/grpc/list_value_return_test.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    # Exclude 'unused' linter for assembly files
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/dot_inline.go
      text: "func `dot[357]`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l2[35]`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l22FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l23FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l24FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l25FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l210FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l212FloatByte`"

run:
  timeout: 5m
  build-tags:
    - integrationTest
    - integrationTestSlow
