linters:
  disable:
    - errcheck
  enable:
    - misspell
    - bodyclose
    - gofumpt
    - exhaustive
    - govet
    - unused
    - nolintlint
    - errorlint
    - forbidigo
linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    # Default: ["^(fmt\\.Print(|f|ln)|print|println)$"]
    forbid:
      # Built-in bootstrapping functions.
      - ^print(ln)?$
      # Optional message that gets included in error reports.
      - p: ^fmt\.Print.*$
        msg: Do not commit print statements.      
      # Forbid spew Dump, whether it is called as function or method.
      # Depends on analyze-types below.
      - ^spew\.(ConfigState\.)?Dump$
    # Exclude godoc examples from forbidigo checks.
    # Default: true
    exclude-godoc-examples: true


  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    default-signifies-exhaustive: true
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Default: true
    errorf: true
    # Permit more than 1 %w verb, valid per Go 1.20 (Requires errorf:true)
    # Default: true
    errorf-multi: true
    # Check for plain type assertions and type switches.
    # Default: true
    asserts: true
    # Check for plain error comparisons.
    # Default: true
    comparison: true
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "S1034"
    - linters:
        - staticcheck
      text: "SA1029:"
    - linters:
        - staticcheck
      text: "SA1015:"
    - linters:
        - staticcheck
      text: "SA5011"
    - linters:
        - govet
      text: "composites"
    - linters:
        - staticcheck
      path: ^adapters/handlers/grpc/v1\/(?:[^\/]+\/)*[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
    - linters:
        - staticcheck
      path: ^test/acceptance/grpc\/[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/prepare_reply.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/parse_search_request.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/batch_parse_request.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/service.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: test/acceptance/grpc/grpc_test_deprecated.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: adapters/handlers/grpc/v1/mapping.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: test/acceptance/grpc/list_value_return_test.go
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API
    - linters:
        - staticcheck
      path: usecases/auth/authentication/oidc/middleware_test.go
      text: 'SA1019' # jwt.StandardClaims is deprecated, but for the purpose of this test, this doesn't matter
    # Exclude 'unused' linter for assembly files
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/dot_inline.go
      text: "func `dot[357]`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l2[35]`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l22FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l23FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l24FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l25FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l210FloatByte`"
    - linters:
        - unused
      path: adapters/repos/db/vector/hnsw/distancer/asm/l2_inline.go
      text: "func `l212FloatByte`"
    - linters: # exclude tests
        - forbidigo
      path: test/*
    - linters: # exclude tools
        - forbidigo
      path: tools/*
    - linters: # exclude file
        - forbidigo
      path: adapters/repos/db/vector/hnsw/debug.go
    - linters: # exclude file
        - forbidigo
      path: adapters/repos/db/vector/.*/dump.go


run:
  timeout: 5m
  build-tags:
    - integrationTest
    - integrationTestSlow
