linters:
  disable:
    - errcheck
  enable:
    - misspell
    - bodyclose
    - gofumpt
    - exhaustive
    - govet
    - unused
    - nolintlint
linters-settings:
  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    default-signifies-exhaustive: true
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "S1034"
    - linters:
        - staticcheck
      text: "SA1029:"
    - linters:
        - staticcheck
      text: "SA1015:"
    - linters:
        - staticcheck
      text: "SA5011"
    - linters:
        - govet
      text: "composites"
    - linters:
        - staticcheck
      path: ^adapters/handlers/grpc/v1\/(?:[^\/]+\/)*[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
    - linters:
        - staticcheck
      path: ^test/acceptance/grpc\/[^\/]+\.go$
      text: 'SA1019' # TODO: remove this once deprecated gRPC fields are removed from API implementation
run:
  build-tags:
    - integrationTest
    - integrationTestSlow
