before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/weaviate-server
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -extldflags "-static"
      - -X github.com/weaviate/weaviate/usecases/build.Branch={{ .Env.GIT_BRANCH }}
      - -X github.com/weaviate/weaviate/usecases/build.Revision={{ .Env.GIT_REVISION }}
      - -X github.com/weaviate/weaviate/usecases/build.BuildUser={{ .Env.BUILD_USER }}
      - -X github.com/weaviate/weaviate/usecases/build.BuildDate={{ .Env.BUILD_DATE }}

# create a "fat" binary for MacOS
universal_binaries:
  - replace: true
