with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{ snakecase .InterfaceName }}.go"
recursive: true
packages:
  github.com/weaviate/weaviate/cluster/replication:
    interfaces:
      OpProducer:
      OpConsumer:
      TimeProvider:
      Timer:
  github.com/weaviate/weaviate/cluster/replication/types:
    interfaces:
      ReplicationFSMReader:
      Manager:
      FSMUpdater:
      ReplicaCopier:
  github.com/weaviate/weaviate/cluster/schema/types:
    interfaces:
      SchemaReader:
  github.com/weaviate/weaviate/usecases/auth/authorization:
    interfaces:
      Authorizer:
