with-expecter: True
recursive: true
inpackage: true
dir: "{{ .InterfaceDir }}"
outpkg: "{{ .PackageName }}"
filename: "mock_{{ snakecase .InterfaceName }}.go"
packages:
  github.com/weaviate/weaviate/adapters/repos/db/lsmkv:
    interfaces:
      BucketCreator:
