# Dockerfile for production purposes.
# Read docs/development.md for more information

# vi: ft=dockerfile

###############################################################################
# Base build image
FROM golang:1.11-alpine AS build_base
RUN apk add bash ca-certificates git gcc g++ libc-dev
WORKDIR /go/src/github.com/semi-technologies/weaviate
ENV GO111MODULE=on
# Populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
RUN go mod download

###############################################################################
# This image builds the weavaite server
FROM build_base AS server_builder
COPY . .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags '-w -extldflags "-static"' ./cmd/weaviate-server

###############################################################################
# This image builds the contextionary fixtures.
FROM alpine:3.8 AS contextionary_fixture_builder
RUN apk add --no-cache curl
RUN apk add --no-cache jq
RUN apk add --no-cache bash
COPY ./tools/download_latest_contextionary.sh ./tools/
RUN ./tools/download_latest_contextionary.sh

###############################################################################
# This is the base image for running waviates configurations; contains the executable & contextionary
FROM alpine AS weaviate_base
COPY --from=server_builder /go/bin/weaviate-server /bin/weaviate
COPY --from=build_base /etc/ssl/certs /etc/ssl/certs
COPY --from=contextionary_fixture_builder ./contextionary/contextionary.idx /contextionary/contextionary.idx
COPY --from=contextionary_fixture_builder ./contextionary/contextionary.knn /contextionary/contextionary.knn
COPY --from=contextionary_fixture_builder ./contextionary/stopwords.json /contextionary/stopwords.json
ENTRYPOINT ["/bin/weaviate"]

###############################################################################
# Development configuration with demo dataset
FROM weaviate_base AS janus
COPY ./tools/dev/schema /schema
COPY ./tools/dev/config.docker.yaml /weaviate.conf.yaml
CMD [ "--host", "0.0.0.0", "--port", "8080", "--scheme", "http", "--config", "janusgraph_docker"]
