apiVersion: v1
kind: Pod
metadata:
  name: alpine-interactive
  annotations:
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: "100m"
    sidecar.istio.io/proxyMemory: "128Mi"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - weaviate
        topologyKey: kubernetes.io/hostname
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    stdin: true
    tty: true
    resources:
      requests:
        cpu: "4000m"
        memory: "2Gi"
        ephemeral-storage: "1Gi"
      limits:
        cpu: "8000m"
        memory: "6Gi"
        ephemeral-storage: "2Gi"