package commands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/tmp/models"
)

// NewWeaviateCommandsUpdateParams creates a new WeaviateCommandsUpdateParams object
// with the default values initialized.
func NewWeaviateCommandsUpdateParams() WeaviateCommandsUpdateParams {
	var ()
	return WeaviateCommandsUpdateParams{}
}

// WeaviateCommandsUpdateParams contains all the bound params for the weaviate commands update operation
// typically these are obtained from a http.Request
//
// swagger:parameters weaviate.commands.update
type WeaviateCommandsUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: body
	*/
	Body *models.CommandUpdate
	/*Unique command ID.
	  Required: true
	  In: path
	*/
	CommandID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *WeaviateCommandsUpdateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CommandUpdate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	rCommandID, rhkCommandID, _ := route.Params.GetOK("commandId")
	if err := o.bindCommandID(rCommandID, rhkCommandID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WeaviateCommandsUpdateParams) bindCommandID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.CommandID = raw

	return nil
}
