package commands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWeaviateCommandsDeleteParams creates a new WeaviateCommandsDeleteParams object
// with the default values initialized.
func NewWeaviateCommandsDeleteParams() WeaviateCommandsDeleteParams {
	var ()
	return WeaviateCommandsDeleteParams{}
}

// WeaviateCommandsDeleteParams contains all the bound params for the weaviate commands delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters weaviate.commands.delete
type WeaviateCommandsDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Unique command ID.
	  Required: true
	  In: path
	*/
	CommandID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *WeaviateCommandsDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rCommandID, rhkCommandID, _ := route.Params.GetOK("commandId")
	if err := o.bindCommandID(rCommandID, rhkCommandID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WeaviateCommandsDeleteParams) bindCommandID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.CommandID = raw

	return nil
}
