//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/weaviate/weaviate/entities/models"
)

// NodesBatchStatusGetOKCode is the HTTP code returned for type NodesBatchStatusGetOK
const NodesBatchStatusGetOKCode int = 200

/*
NodesBatchStatusGetOK Nodes batch stats successfully returned

swagger:response nodesBatchStatusGetOK
*/
type NodesBatchStatusGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.NodesBatchStatusResponse `json:"body,omitempty"`
}

// NewNodesBatchStatusGetOK creates NodesBatchStatusGetOK with default headers values
func NewNodesBatchStatusGetOK() *NodesBatchStatusGetOK {

	return &NodesBatchStatusGetOK{}
}

// WithPayload adds the payload to the nodes batch status get o k response
func (o *NodesBatchStatusGetOK) WithPayload(payload *models.NodesBatchStatusResponse) *NodesBatchStatusGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes batch status get o k response
func (o *NodesBatchStatusGetOK) SetPayload(payload *models.NodesBatchStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesBatchStatusGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NodesBatchStatusGetUnauthorizedCode is the HTTP code returned for type NodesBatchStatusGetUnauthorized
const NodesBatchStatusGetUnauthorizedCode int = 401

/*
NodesBatchStatusGetUnauthorized Unauthorized or invalid credentials.

swagger:response nodesBatchStatusGetUnauthorized
*/
type NodesBatchStatusGetUnauthorized struct {
}

// NewNodesBatchStatusGetUnauthorized creates NodesBatchStatusGetUnauthorized with default headers values
func NewNodesBatchStatusGetUnauthorized() *NodesBatchStatusGetUnauthorized {

	return &NodesBatchStatusGetUnauthorized{}
}

// WriteResponse to the client
func (o *NodesBatchStatusGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// NodesBatchStatusGetForbiddenCode is the HTTP code returned for type NodesBatchStatusGetForbidden
const NodesBatchStatusGetForbiddenCode int = 403

/*
NodesBatchStatusGetForbidden Forbidden

swagger:response nodesBatchStatusGetForbidden
*/
type NodesBatchStatusGetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewNodesBatchStatusGetForbidden creates NodesBatchStatusGetForbidden with default headers values
func NewNodesBatchStatusGetForbidden() *NodesBatchStatusGetForbidden {

	return &NodesBatchStatusGetForbidden{}
}

// WithPayload adds the payload to the nodes batch status get forbidden response
func (o *NodesBatchStatusGetForbidden) WithPayload(payload *models.ErrorResponse) *NodesBatchStatusGetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes batch status get forbidden response
func (o *NodesBatchStatusGetForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesBatchStatusGetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NodesBatchStatusGetInternalServerErrorCode is the HTTP code returned for type NodesBatchStatusGetInternalServerError
const NodesBatchStatusGetInternalServerErrorCode int = 500

/*
NodesBatchStatusGetInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response nodesBatchStatusGetInternalServerError
*/
type NodesBatchStatusGetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewNodesBatchStatusGetInternalServerError creates NodesBatchStatusGetInternalServerError with default headers values
func NewNodesBatchStatusGetInternalServerError() *NodesBatchStatusGetInternalServerError {

	return &NodesBatchStatusGetInternalServerError{}
}

// WithPayload adds the payload to the nodes batch status get internal server error response
func (o *NodesBatchStatusGetInternalServerError) WithPayload(payload *models.ErrorResponse) *NodesBatchStatusGetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes batch status get internal server error response
func (o *NodesBatchStatusGetInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesBatchStatusGetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
