//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// NewSchemaObjectsPropertiesUpdateParams creates a new SchemaObjectsPropertiesUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchemaObjectsPropertiesUpdateParams() *SchemaObjectsPropertiesUpdateParams {
	return &SchemaObjectsPropertiesUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchemaObjectsPropertiesUpdateParamsWithTimeout creates a new SchemaObjectsPropertiesUpdateParams object
// with the ability to set a timeout on a request.
func NewSchemaObjectsPropertiesUpdateParamsWithTimeout(timeout time.Duration) *SchemaObjectsPropertiesUpdateParams {
	return &SchemaObjectsPropertiesUpdateParams{
		timeout: timeout,
	}
}

// NewSchemaObjectsPropertiesUpdateParamsWithContext creates a new SchemaObjectsPropertiesUpdateParams object
// with the ability to set a context for a request.
func NewSchemaObjectsPropertiesUpdateParamsWithContext(ctx context.Context) *SchemaObjectsPropertiesUpdateParams {
	return &SchemaObjectsPropertiesUpdateParams{
		Context: ctx,
	}
}

// NewSchemaObjectsPropertiesUpdateParamsWithHTTPClient creates a new SchemaObjectsPropertiesUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchemaObjectsPropertiesUpdateParamsWithHTTPClient(client *http.Client) *SchemaObjectsPropertiesUpdateParams {
	return &SchemaObjectsPropertiesUpdateParams{
		HTTPClient: client,
	}
}

/*
SchemaObjectsPropertiesUpdateParams contains all the parameters to send to the API endpoint

	for the schema objects properties update operation.

	Typically these are written to a http.Request.
*/
type SchemaObjectsPropertiesUpdateParams struct {

	// Body.
	Body *models.Property

	// ClassName.
	ClassName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the schema objects properties update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchemaObjectsPropertiesUpdateParams) WithDefaults() *SchemaObjectsPropertiesUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the schema objects properties update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchemaObjectsPropertiesUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) WithTimeout(timeout time.Duration) *SchemaObjectsPropertiesUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) WithContext(ctx context.Context) *SchemaObjectsPropertiesUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) WithHTTPClient(client *http.Client) *SchemaObjectsPropertiesUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) WithBody(body *models.Property) *SchemaObjectsPropertiesUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) SetBody(body *models.Property) {
	o.Body = body
}

// WithClassName adds the className to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) WithClassName(className string) *SchemaObjectsPropertiesUpdateParams {
	o.SetClassName(className)
	return o
}

// SetClassName adds the className to the schema objects properties update params
func (o *SchemaObjectsPropertiesUpdateParams) SetClassName(className string) {
	o.ClassName = className
}

// WriteToRequest writes these params to a swagger request
func (o *SchemaObjectsPropertiesUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param className
	if err := r.SetPathParam("className", o.ClassName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
