//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package vectorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// NewVectorizationStartParams creates a new VectorizationStartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVectorizationStartParams() *VectorizationStartParams {
	return &VectorizationStartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVectorizationStartParamsWithTimeout creates a new VectorizationStartParams object
// with the ability to set a timeout on a request.
func NewVectorizationStartParamsWithTimeout(timeout time.Duration) *VectorizationStartParams {
	return &VectorizationStartParams{
		timeout: timeout,
	}
}

// NewVectorizationStartParamsWithContext creates a new VectorizationStartParams object
// with the ability to set a context for a request.
func NewVectorizationStartParamsWithContext(ctx context.Context) *VectorizationStartParams {
	return &VectorizationStartParams{
		Context: ctx,
	}
}

// NewVectorizationStartParamsWithHTTPClient creates a new VectorizationStartParams object
// with the ability to set a custom HTTPClient for a request.
func NewVectorizationStartParamsWithHTTPClient(client *http.Client) *VectorizationStartParams {
	return &VectorizationStartParams{
		HTTPClient: client,
	}
}

/*
VectorizationStartParams contains all the parameters to send to the API endpoint

	for the vectorization start operation.

	Typically these are written to a http.Request.
*/
type VectorizationStartParams struct {
	// Body.
	Body *models.CollectionVectorizationRequest

	// CollectionName.
	CollectionName string

	// TargetVector.
	TargetVector string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vectorization start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VectorizationStartParams) WithDefaults() *VectorizationStartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vectorization start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VectorizationStartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vectorization start params
func (o *VectorizationStartParams) WithTimeout(timeout time.Duration) *VectorizationStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vectorization start params
func (o *VectorizationStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vectorization start params
func (o *VectorizationStartParams) WithContext(ctx context.Context) *VectorizationStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vectorization start params
func (o *VectorizationStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vectorization start params
func (o *VectorizationStartParams) WithHTTPClient(client *http.Client) *VectorizationStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vectorization start params
func (o *VectorizationStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the vectorization start params
func (o *VectorizationStartParams) WithBody(body *models.CollectionVectorizationRequest) *VectorizationStartParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the vectorization start params
func (o *VectorizationStartParams) SetBody(body *models.CollectionVectorizationRequest) {
	o.Body = body
}

// WithCollectionName adds the collectionName to the vectorization start params
func (o *VectorizationStartParams) WithCollectionName(collectionName string) *VectorizationStartParams {
	o.SetCollectionName(collectionName)
	return o
}

// SetCollectionName adds the collectionName to the vectorization start params
func (o *VectorizationStartParams) SetCollectionName(collectionName string) {
	o.CollectionName = collectionName
}

// WithTargetVector adds the targetVector to the vectorization start params
func (o *VectorizationStartParams) WithTargetVector(targetVector string) *VectorizationStartParams {
	o.SetTargetVector(targetVector)
	return o
}

// SetTargetVector adds the targetVector to the vectorization start params
func (o *VectorizationStartParams) SetTargetVector(targetVector string) {
	o.TargetVector = targetVector
}

// WriteToRequest writes these params to a swagger request
func (o *VectorizationStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param collectionName
	if err := r.SetPathParam("collectionName", o.CollectionName); err != nil {
		return err
	}

	// path param targetVector
	if err := r.SetPathParam("targetVector", o.TargetVector); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
