//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package namespaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResumeNamespaceParams creates a new ResumeNamespaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResumeNamespaceParams() *ResumeNamespaceParams {
	return &ResumeNamespaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResumeNamespaceParamsWithTimeout creates a new ResumeNamespaceParams object
// with the ability to set a timeout on a request.
func NewResumeNamespaceParamsWithTimeout(timeout time.Duration) *ResumeNamespaceParams {
	return &ResumeNamespaceParams{
		timeout: timeout,
	}
}

// NewResumeNamespaceParamsWithContext creates a new ResumeNamespaceParams object
// with the ability to set a context for a request.
func NewResumeNamespaceParamsWithContext(ctx context.Context) *ResumeNamespaceParams {
	return &ResumeNamespaceParams{
		Context: ctx,
	}
}

// NewResumeNamespaceParamsWithHTTPClient creates a new ResumeNamespaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewResumeNamespaceParamsWithHTTPClient(client *http.Client) *ResumeNamespaceParams {
	return &ResumeNamespaceParams{
		HTTPClient: client,
	}
}

/*
ResumeNamespaceParams contains all the parameters to send to the API endpoint

	for the resume namespace operation.

	Typically these are written to a http.Request.
*/
type ResumeNamespaceParams struct {

	/* NamespaceID.

	   The name of the namespace.
	*/
	NamespaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resume namespace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResumeNamespaceParams) WithDefaults() *ResumeNamespaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resume namespace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResumeNamespaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resume namespace params
func (o *ResumeNamespaceParams) WithTimeout(timeout time.Duration) *ResumeNamespaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resume namespace params
func (o *ResumeNamespaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resume namespace params
func (o *ResumeNamespaceParams) WithContext(ctx context.Context) *ResumeNamespaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resume namespace params
func (o *ResumeNamespaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resume namespace params
func (o *ResumeNamespaceParams) WithHTTPClient(client *http.Client) *ResumeNamespaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resume namespace params
func (o *ResumeNamespaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespaceID adds the namespaceID to the resume namespace params
func (o *ResumeNamespaceParams) WithNamespaceID(namespaceID string) *ResumeNamespaceParams {
	o.SetNamespaceID(namespaceID)
	return o
}

// SetNamespaceID adds the namespaceId to the resume namespace params
func (o *ResumeNamespaceParams) SetNamespaceID(namespaceID string) {
	o.NamespaceID = namespaceID
}

// WriteToRequest writes these params to a swagger request
func (o *ResumeNamespaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace_id
	if err := r.SetPathParam("namespace_id", o.NamespaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
