//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

// Package rest Weaviate
//
//	Cloud-native, modular vector database
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /v1
//	Version: 1.23.2
//	Contact: Weaviate<hello@weaviate.io> https://github.com/weaviate
//
//	Consumes:
//	  - application/json
//	  - application/yaml
//
//	Produces:
//	  - application/json
//
// swagger:meta
package rest
