/*                          _       _
 *__      _____  __ ___   ___  __ _| |_ ___
 *\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
 * \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
 *  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
 *
 * Copyright © 2016 - 2019 Weaviate. All rights reserved.
 * LICENSE: https://github.com/semi-technologies/weaviate/blob/develop/LICENSE.md
 * DESIGN & CONCEPT: Bob van Luijt (@bobvanluijt)
 * CONTACT: hello@semi.technology
 */package main

var sampleTexts = []document{{
	ID:   0,
	Name: "Brexit",
	Content: `Brexit (/ˈbrɛksɪt, ˈbrɛɡzɪt/[1]; a portmanteau of "British" and "exit") is the potential withdrawal of the United Kingdom (UK) from the European Union (EU). Following a referendum held on 23 June 2016 in which 51.9 per cent of those voting supported leaving the EU, the invocation of Article 50 of the Treaty on European Union started a two-year process which was due to conclude with the UK's exit on 29 March 2019, a deadline which was later extended to 31 October 2019.[2]

Withdrawal has been advocated by Eurosceptics, both left-wing and right-wing, while pro-Europeanists, who also span the political spectrum, have advocated continued membership and maintaining the customs union and single market. The UK joined the European Communities (EC) in 1973 under the Conservative government of Edward Heath, with continued membership endorsed by a referendum in 1975. In the 1970s and 1980s, withdrawal from the EC was advocated mainly by the political left, with the Labour Party's 1983 election manifesto advocating full withdrawal. From the 1990s, opposition to further European integration came mainly from the right, and divisions within the Conservative Party led to rebellion over the Maastricht Treaty in 1992. The growth of the UK Independence Party (UKIP) in the early 2010s and the influence of the cross-party People's Pledge campaign have been described as influential in bringing about a referendum. The Conservative Prime Minister, David Cameron, pledged during the campaign for the 2015 UK General Election to hold a new referendum—a promise which he fulfilled in 2016 following pressure from the Eurosceptic wing of his party. Cameron, who had campaigned to remain, resigned after the result and was succeeded by Theresa May, his former Home Secretary. She called a snap general election less than a year later, but lost her overall majority. Her minority government is supported in key votes by the Democratic Unionist Party.

On 29 March 2017, the Government of the United Kingdom invoked Article 50 of the Treaty on European Union. May announced the government's intention not to seek permanent membership of the European single market or the EU customs union after leaving the EU and promised to repeal the European Communities Act of 1972 and incorporate existing European Union law into UK domestic law. Negotiations with the EU officially started in June 2017. In November 2018, the Draft Withdrawal Agreement and Outline Political Declaration, agreed between the UK Government and the EU, was published. The House of Commons voted against the deal by a margin of 432 to 202 (the largest parliamentary defeat in history for a sitting UK government) on 15 January 2019, and again on 12 March with a margin of 391 to 242 against the deal. On 14 March 2019, the House of Commons voted for the Prime Minister, Theresa May, to ask the EU for such an extension of the period allowed for the negotiation. Members from across the House of Commons rejected the deal with the leadership of the Labour Party stating in public debates in the House of Commons that any deal must maintain a customs union and single market, and with a large percentage of its members rejecting the Irish backstop as it is currently drafted in the EU withdrawal agreement. Opponents of the EU Withdrawl Agreement cited concerns that the agreement as drafted could plunge Northern Ireland into a conflict and spark a return of The Troubles as a result of Brexit.

The broad consensus among economists is that Brexit will likely reduce the UK's real per capita income in the medium term and long term, and that the Brexit referendum itself had damaged the economy. Studies on effects since the referendum show a reduction in GDP, trade and investment, as well as household losses from increased inflation. Brexit is likely to reduce immigration from European Economic Area (EEA) countries to the UK, and poses challenges for UK higher education and academic research. As of March 2019, the size of the "divorce bill"—the UK's inheritance of existing EU trade agreements—and relations with Ireland and other EU member states remains uncertain. The precise impact on the UK depends on whether the process will be a "hard" or "soft" Brexit.`,
},
	{
		ID:             1,
		Name:           "Car",
		SampleBoolProp: true,
		Content: `A car (or automobile) is a wheeled motor vehicle used for transportation. Most definitions of car say they run primarily on roads, seat one to eight people, have four tires, and mainly transport people rather than goods.[2][3]

Cars came into global use during the 20th century, and developed economies depend on them. The year 1886 is regarded as the birth year of the modern car when German inventor Karl Benz patented his Benz Patent-Motorwagen. Cars became widely available in the early 20th century. One of the first cars accessible to the masses was the 1908 Model T, an American car manufactured by the Ford Motor Company. Cars were rapidly adopted in the US, where they replaced animal-drawn carriages and carts, but took much longer to be accepted in Western Europe and other parts of the world.

Cars have controls for driving, parking, passenger comfort, and safety, and controlling a variety of lights. Over the decades, additional features and controls have been added to vehicles, making them progressively more complex. These include rear reversing cameras, air conditioning, navigation systems, and in-car entertainment. Most cars in use in the 2010s are propelled by an internal combustion engine, fueled by the combustion of fossil fuels. Electric cars, which were invented early in the history of the car, began to become commercially available in 2008.

There are costs and benefits to car use. The costs include acquiring the vehicle, interest payments (if the car is financed), repairs and maintenance, fuel, depreciation, driving time, parking fees, taxes, and insurance.[4] The costs to society include maintaining roads, land use, road congestion, air pollution, public health, health care, and disposing of the vehicle at the end of its life. Road traffic accidents are the largest cause of injury-related deaths worldwide.[5]

The benefits include on-demand transportation, mobility, independence, and convenience.[6] The societal benefits include economic benefits, such as job and wealth creation from the automotive industry, transportation provision, societal well-being from leisure and travel opportunities, and revenue generation from the taxes. People's ability to move flexibly from place to place has far-reaching implications for the nature of societies.[7] There are around 1 billion cars in use worldwide. The numbers are increasing rapidly, especially in China, India and other newly industrialized countries.[8]`,
	}, {
		ID:   2,
		Name: "Yogurt",
		Content: `Yogurt (/ˈjoʊɡərt/ or /ˈjɒɡərt/; from Turkish: yoğurt), also spelled yoghurt, yogourt or yoghourt, is a food produced by bacterial fermentation of milk.[1] The bacteria used to make yogurt are known as yogurt cultures. The fermentation of lactose by these bacteria produces lactic acid, which acts on milk protein to give yogurt its texture and characteristic tart flavor.[1] Cow's milk is commonly available worldwide and, as such, is the milk most commonly used to make yogurt. Milk from water buffalo, goats, ewes, mares, camels, and yaks is also used to produce yogurt where available locally. The milk used may be homogenized or not, even pasteurized or raw. Each type of milk produces substantially different results.

Yogurt is produced using a culture of Lactobacillus delbrueckii subsp. bulgaricus and Streptococcus thermophilus bacteria. In addition, other lactobacilli and bifidobacteria are sometimes added during or after culturing yogurt. Some countries require yogurt to contain a certain amount of colony-forming units (CFU) of bacteria; in China, for example, the requirement for the number of lactobacillus bacteria is at least 1 million CFU per milliliter.[2]

To produce yogurt, milk is first heated, usually to about 85 °C (185 °F), to denature the milk proteins so that they do not form curds. After heating, the milk is allowed to cool to about 45 °C (113 °F).[3] The bacterial culture is mixed in, and that temperature of 45 °C is maintained for 4 to 12 hours to allow fermentation to occur.[4]`,
	}, {
		ID:   3,
		Name: "Microphone",
		Content: `A microphone, colloquially nicknamed mic or mike (/maɪk/),[1] is a transducer that converts sound into an electrical signal.

Microphones are used in many applications such as telephones, hearing aids, public address systems for concert halls and public events, motion picture production, live and recorded audio engineering, sound recording, two-way radios, megaphones, radio and television broadcasting, and in computers for recording voice, speech recognition, VoIP, and for non-acoustic purposes such as ultrasonic sensors or knock sensors.

Several different types of microphone are in use, which employ different methods to convert the air pressure variations of a sound wave to an electrical signal. The most common are the dynamic microphone, which uses a coil of wire suspended in a magnetic field; the condenser microphone, which uses the vibrating diaphragm as a capacitor plate, and the piezoelectric microphone, which uses a crystal of piezoelectric material. Microphones typically need to be connected to a preamplifier before the signal can be recorded or reproduced.`,
	}, {
		ID:   4,
		Name: "Software",
		Content: `Computer software, or simply software, is a collection of data or computer instructions that tell the computer how to work. This is in contrast to physical hardware, from which the system is built and actually performs the work. In computer science and software engineering, computer software is all information processed by computer systems, programs and data. Computer software includes computer programs, libraries and related non-executable data, such as online documentation or digital media. Computer hardware and software require each other and neither can be realistically used on its own.

At the lowest programming level,[clarification needed] executable code consists of machine language instructions supported by an individual processor—typically a central processing unit (CPU) or a graphics processing unit (GPU). A machine language consists of groups of binary values signifying processor instructions that change the state of the computer from its preceding state. For example, an instruction may change the value stored in a particular storage location in the computer—an effect that is not directly observable to the user. An instruction may also invoke one of many input or output operations, for example displaying some text on a computer screen; causing state changes which should be visible to the user. The processor executes the instructions in the order they are provided, unless it is instructed to "jump" to a different instruction, or is interrupted by the operating system. As of 2015, most personal computers, smartphone devices and servers have processors with multiple execution units or multiple processors performing computation together, and computing has become a much more concurrent activity than in the past.

The majority of software is written in high-level programming languages. They are easier and more efficient for programmers because they are closer to natural languages than machine languages.[1] High-level languages are translated into machine language using a compiler or an interpreter or a combination of the two. Software may also be written in a low-level assembly language, which has strong correspondence to the computer's machine language instructions and is translated into machine language using an assembler.`,
	}, {
		ID:   5,
		Name: "Book",
		Content: `As a physical object, a book is a stack of usually rectangular pages (made of papyrus, parchment, vellum, or paper) oriented with one edge tied, sewn, or otherwise fixed together and then bound to the flexible spine of a protective cover of heavier, relatively inflexible material.[1] The technical term for this physical arrangement is codex (in the plural, codices). In the history of hand-held physical supports for extended written compositions or records, the codex replaces its immediate predecessor, the scroll. A single sheet in a codex is a leaf, and each side of a leaf is a page.

As an intellectual object, a book is prototypically a composition of such great length that it takes a considerable investment of time to compose and a still considerable, though not so extensive, investment of time to read. This sense of book has a restricted and an unrestricted sense. In the restricted sense, a book is a self-sufficient section or part of a longer composition, a usage that reflects the fact that, in antiquity, long works had to be written on several scrolls, and each scroll had to be identified by the book it contained. So, for instance, each part of Aristotle's Physics is called a book, as of course, the Bible encompasses many different books. In the unrestricted sense, a book is the compositional whole of which such sections, whether called books or chapters or parts, are parts.

The intellectual content in a physical book need not be a composition, nor even be called a book. Books can consist only of drawings, engravings, or photographs, or such things as crossword puzzles or cut-out dolls. In a physical book, the pages can be left blank or can feature an abstract set of lines as support for on-going entries, i.e., an account book, an appointment book, a log book, an autograph book, a notebook, a diary or day book, or a sketchbook. Some physical books are made with pages thick and sturdy enough to support other physical objects, like a scrapbook or photograph album. Books may be distributed in electronic form as e-books and other formats.

Although in ordinary academic parlance a monograph is understood to be a specialist academic work, rather than a reference work on a single scholarly subject, in library and information science monograph denotes more broadly any non-serial publication complete in one volume (book) or a finite number of volumes (even a novel like Proust's seven-volume In Search of Lost Time), in contrast to serial publications like a magazine, journal, or newspaper. An avid reader or collector of books or a book lover is a bibliophile or colloquially, "bookworm". A shop where books are bought and sold is a bookshop or bookstore. Books are also sold elsewhere. Books can also be borrowed from libraries. Google has estimated that as of 2010, approximately 130,000,000 distinct titles had been published.[2] In some wealthier nations, the sale of printed books has decreased because of the increased usage of e-books.[3]`,
	},
	{
		ID:      6,
		Name:    "Melon",
		Content: `A melon is any of various plants of the family Cucurbitaceae with sweet edible, fleshy fruit. The word "melon" can refer to either the plant or specifically to the fruit. Botanically, a melon is a kind of berry, specifically a "pepo". The word melon derives from Latin melopepo,[1][2] which is the latinization of the Greek μηλοπέπων (mēlopepōn), meaning "melon",[3] itself a compound of μῆλον (mēlon), "apple, treefruit (of any kind)"[4] and πέπων (pepōn), amongst others "a kind of gourd or melon".[5] Many different cultivars have been produced, particularly of cantaloupes.`,
	},
	{
		ID:      7,
		Name:    "Schnitzel",
		Content: `A schnitzel is meat, usually thinned by pounding with a meat tenderizer, that is fried in some kind of oil or fat. The term is most commonly used to refer to meats coated with flour, beaten eggs, and bread crumbs, and then fried, but some variants such as Walliser Schnitzel are not breaded. Originating in Austria, the breaded schnitzel is popular in many countries and made using either chicken, veal, mutton, beef, turkey, or pork. It is very similar to the French dish escalope, tonkatsu in Japan, and the milanesa of Mexico, Uruguay, Argentina, and Brazil.`,
	},
	{
		ID:   8,
		Name: "Pork",
		Content: `Pork is the culinary name for meat from a domestic pig (Sus scrofa domesticus). It is the most commonly consumed meat worldwide,[1] with evidence of pig husbandry dating back to 5000 BC.

Pork is eaten both freshly cooked and preserved. Curing extends the shelf life of the pork products. Ham, smoked pork, gammon, bacon and sausage are examples of preserved pork. Charcuterie is the branch of cooking devoted to prepared meat products, many from pork.

Pork is the most popular meat in Eastern and Southeastern Asia, and is also very common in the Western world, especially in Central Europe. It is highly prized in Asian cuisines for its fat content and pleasant texture. Consumption of pork is forbidden by Jewish, Muslim, and Rastafarian dietary law, for religious reasons, with several suggested possible causes.`,
	},
	{
		ID:   9,
		Name: "Restaurant",
		Content: `A restaurant (French: [ʁɛstoʁɑ̃] (About this soundlisten)), or an eatery, is a business which prepares and serves food and drinks to customers in exchange for money. Meals are generally served and eaten on the premises, but many restaurants also offer take-out and food delivery services. Restaurants vary greatly in appearance and offerings, including a wide variety of cuisines and service models ranging from inexpensive fast food restaurants and cafeterias to mid-priced family restaurants, to high-priced luxury establishments.

In Western countries, most mid- to high-range restaurants serve alcoholic beverages such as beer and wine. Some restaurants serve all the major meals, such as breakfast, lunch, and dinner (e.g., major fast food chains, diners, hotel restaurants, and airport restaurants). Other restaurants may only serve a single meal (for example, a pancake house may only serve breakfast) or they may serve two meals (e.g., lunch and dinner).`,
	},
	{
		ID:   10,
		Name: "McDonalds",
		Content: `McDonald's is an American fast food company, founded in 1940 as a restaurant operated by Richard and Maurice McDonald, in San Bernardino, California, United States. They rechristened their business as a hamburger stand, and later turned the company into a franchise, with the Golden Arches logo being introduced in 1953 at a location in Phoenix, Arizona. In 1955, Ray Kroc, a businessman, joined the company as a franchise agent and proceeded to purchase the chain from the McDonald brothers. McDonald's had its original headquarters in Oak Brook, Illinois, but moved its global headquarters to Chicago in early 2018.[5][6][7]

McDonald's is the world's largest restaurant chain by revenue,[8] serving over 69 million customers daily in over 100 countries[9] across 37,855 outlets as of 2018.[10][11] Although McDonald's is best known for its hamburgers, cheeseburgers and french fries, they also feature chicken products, breakfast items, soft drinks, milkshakes, wraps, and desserts. In response to changing consumer tastes and a negative backlash because of the unhealthiness of their food,[12] the company has added to its menu salads, fish, smoothies, and fruit. The McDonald's Corporation revenues come from the rent, royalties, and fees paid by the franchisees, as well as sales in company-operated restaurants. According to two reports published in 2018, McDonald's is the world's fourth-largest private employer with 1.7 million employees (behind Walmart with 2.3 million employees).[13][14]`,
	},
	{
		ID:   11,
		Name: "Potato",
		Content: `The potato is a starchy, tuberous crop from the perennial nightshade Solanum tuberosum. In many contexts, potato refers to the edible tuber, but it can also refer to the plant itself.[2] Common or slang terms include tater,[a] tattie and spud. Potatoes were introduced to Europe in the second half of the 16th century by the Spanish. Today they are a staple food in many parts of the world and an integral part of much of the world's food supply. As of 2014, potatoes were the world's fourth-largest food crop after maize (corn), wheat, and rice.[4]

Wild potato species can be found throughout the Americas, from the United States to southern Chile.[5] The potato was originally believed to have been domesticated independently in multiple locations,[6] but later genetic testing of the wide variety of cultivars and wild species traced a single origin for potatoes. In the area of present-day southern Peru and extreme northwestern Bolivia, from a species in the Solanum brevicaule complex, potatoes were domesticated approximately 7,000–10,000 years ago.[7][8][9] In the Andes region of South America, where the species is indigenous, some close relatives of the potato are cultivated.

Following millennia of selective breeding, there are now over 1,000 different types of potatoes.[8] Over 99% of presently cultivated potatoes worldwide descended from varieties that originated in the lowlands of south-central Chile, which have displaced formerly popular varieties from the Andes.[10][11]

The importance of the potato as a food source and culinary ingredient varies by region and is still changing. It remains an essential crop in Europe, especially eastern and central Europe, where per capita production is still the highest in the world, while the most rapid expansion in production over the past few decades has occurred in southern and eastern Asia, with China and India leading the world in overall production as of 2014.

Being a nightshade similar to tomatoes, the vegetative and fruiting parts of the potato contain the toxin solanine and are not fit for human consumption. Normal potato tubers that have been grown and stored properly produce glycoalkaloids in amounts small enough to be negligible to human health, but if green sections of the plant (namely sprouts and skins) are exposed to light, the tuber can accumulate a high enough concentration of glycoalkaloids to affect human health.[12][13]`,
	},
	{
		ID:      12,
		Name:    "Formula 1 car",
		Content: `A Formula One car is a single-seat, open cockpit, open-wheel racing car with substantial front and rear wings, and an engine positioned behind the driver, intended to be used in competition at Formula One racing events. The regulations governing the cars are unique to the championship. The Formula One regulations specify that cars must be constructed by the racing teams themselves, though the design and manufacture can be outsourced.`,
	},
	{
		ID:   13,
		Name: "Motorsports",
		Content: `Motorsport or motor sport is a global term used to encompass the group of competitive sporting events which primarily involve the use of motorised vehicles, whether for racing or non-racing competition. The terminology can also be used to describe forms of competition of two-wheeled motorised vehicles under the banner of motorcycle racing, and includes off-road racing such as motocross.

Four- (or more) wheeled motorsport competition is globally governed by the Fédération Internationale de l'Automobile (FIA); and the Fédération Internationale de Motocyclisme (FIM) governs two-wheeled competition. Likewise, the Union Internationale Motonautique (UIM) governs powerboat racing while the Fédération Aéronautique Internationale (FAI) governs air sports; including airplane racing.`,
	},
	{
		ID:   14,
		Name: "Limousine",
		Content: `A limousine (/ˈlɪməziːn/ or /lɪməˈziːn/)[1] is a luxury vehicle driven by a chauffeur with a partition between the driver's compartment and the passenger's compartment.

A car with a partition and a greatly lengthened wheelbase is called a "stretch limousine".

In some countries, a "limousine service" is a pre-booked hire car with driver, regardless of the type of vehicle.

In German-speaking countries, a Limousine is simply a sedan, while a lengthened-wheelbase car is called Stretch-Limousine.`,
	},
	{
		ID:   15,
		Name: "Public Transportation",
		Content: `Public transport (also known as public transportation, public transit, or mass transit) is transport of passengers by group travel systems available for use by the general public, typically managed on a schedule, operated on established routes, and that charge a posted fee for each trip.[1][2][3] Examples of public transport include city buses, trolleybuses, trams (or light rail) and passenger trains, rapid transit (metro/subway/underground, etc.) and ferries. Public transport between cities is dominated by airlines, coaches, and intercity rail. High-speed rail networks are being developed in many parts of the world.

Most public transport systems run along fixed routes with set embarkation/disembarkation points to a prearranged timetable, with the most frequent services running to a headway (e.g.: "every 15 minutes" as opposed to being scheduled for any specific time of the day). However, most public transport trips include other modes of travel, such as passengers walking or catching bus services to access train stations.[4] Share taxis offer on-demand services in many parts of the world, which may compete with fixed public transport lines, or compliment them, by bringing passengers to interchanges. Paratransit is sometimes used in areas of low demand and for people who need a door-to-door service.[5]

Urban public transit differs distinctly among Asia, North America, and Europe. In Asia, profit-driven, privately-owned and publicly traded mass transit and real estate conglomerates predominantly operate public transit systems [6][7] In North America, municipal transit authorities most commonly run mass transit operations. In Europe, both state-owned and private companies predominantly operate mass transit systems, Public transport services can be profit-driven by use of pay-by-the-distance fares or funded by government subsidies in which flat rate fares are charged to each passenger. Services can be fully profitable through high usership numbers and high farebox recovery ratios, or can be regulated and possibly subsidised from local or national tax revenue. Fully subsidised, free of charge services operate in some towns and cities.

For geographical, historical and economic reasons, differences exist internationally regarding use and extent of public transport. While countries in the Old World tend to have extensive and frequent systems serving their old and dense cities, many cities of the New World have more sprawl and much less comprehensive public transport. The International Association of Public Transport (UITP) is the international network for public transport authorities and operators, policy decision-makers, scientific institutes and the public transport supply and service industry. It has 3,400 members from 92 countries from all over the globe.`,
	},
	{
		ID:   16,
		Name: "Autobahn",
		Content: `The Autobahn IPA: [ˈʔaʊtoˌba:n] (About this soundlisten), German plural Autobahnen) is the federal controlled-access highway system in Germany. The official German term is Bundesautobahn (plural Bundesautobahnen, abbreviated BAB), which translates as "federal motorway". The literal meaning of the word Bundesautobahn is "Federal Auto(mobile) Track".

German Autobahnen are widely known for having no federally mandated speed limit for some classes of vehicles.[1] However, limits are posted (and enforced) in areas that are urbanised, substandard, accident-prone, or under construction. On speed-unrestricted stretches, an advisory speed limit (Richtgeschwindigkeit) of 130 kilometres per hour (81 mph) applies. While going faster is not illegal as such in the absence of a speed limit, it can cause an increased liability in the case of an accident; courts have ruled that an "ideal driver" who is exempt from absolute liability for "inevitable" tort under the law would not exceed Richtgeschwindigkeit.

A 2017 report by the Federal Road Research Institute reported that in 2015 70.4% of the autobahn network had only the advisory speed limit, 6.2% had temporary speed limits due to weather or traffic conditions, and 23.4% had permanent speed limits.[2] Measurements from the German State of Brandenburg in 2006 showed average speeds of 142 km/h (88 mph) on a 6-lane section of autobahn in free-flowing conditions.[3]

Germany's autobahn network has a total length of about 13,000 km (12,996 kilometres (8,075 mi) in 2017[4]), and a density of 36 motorway kilometres per thousand square kilometer (Eurostat) which ranks it among the most dense and longest controlled-access systems in the world, and fifth in density within the EU in 2016 (Netherlands 66, Finland 3). Longer similar systems can be found in the United States (77,540 kilometres (48,180 mi))[5] and in China (136,500 kilometres (84,800 mi)).[6] However both the U.S. and China have an area nearly 30 times bigger than Germany, which demonstrates the high density of Germany's highway system.[7]`,
	},
	{
		ID:   17,
		Name: "Mercedes Benz",
		Content: `Mercedes-Benz (German: [mɛʁˈtseːdəsˌbɛnts] or [-dɛs-][1][2]) is a German global automobile marque and a division of Daimler AG. The brand is known for luxury vehicles, buses, coaches, and trucks. The headquarters is in Stuttgart, Baden-Württemberg. The name first appeared in 1926 under Daimler-Benz. In 2018, Mercedes-Benz was the biggest selling premium vehicle brand in the world, having sold 2.31 million passenger cars.[3]

Mercedes-Benz traces its origins to Daimler-Motoren-Gesellschaft's 1901 Mercedes and Karl Benz's 1886 Benz Patent-Motorwagen, which is widely regarded as the first gasoline-powered automobile. The slogan for the brand is "the best or nothing".[4]`,
	},
	{
		ID:   18,
		Name: "UK Parlament",
		Content: `The Parliament of the United Kingdom of Great Britain and Northern Ireland, commonly known internationally as the UK Parliament, British Parliament, or Westminster Parliament, and domestically simply as Parliament, is the supreme legislative body of the United Kingdom, the Crown dependencies and the British Overseas Territories.[3][4] It alone possesses legislative supremacy and thereby ultimate power over all other political bodies in the UK and the overseas territories. Parliament is bicameral but has three parts, consisting of the Sovereign (the Queen-in-Parliament), the House of Lords, and the House of Commons (the primary chamber).[5][6] The two houses meet in the Palace of Westminster in the City of Westminster, one of the inner boroughs of the capital city, London.

The House of Lords includes two different types of members: the Lords Spiritual, consisting of the most senior bishops of the Church of England, and the Lords Temporal, consisting mainly of life peers, appointed by the Sovereign on the advice of the Prime Minister,[7] and of 92 hereditary peers, sitting either by virtue of holding a royal office, or by being elected by their fellow hereditary peers. Prior to the opening of the Supreme Court in October 2009, the House of Lords also performed a judicial role through the Law Lords.

The House of Commons is an elected chamber with elections to 650 single member constituencies held at least every five years under the first-past-the-post system.[8] The two Houses meet in separate chambers in the Palace of Westminster (commonly known as the Houses of Parliament) in London. By constitutional convention, all government ministers, including the Prime Minister, are members of the House of Commons or, less commonly, the House of Lords and are thereby accountable to the respective branches of the legislature. Most cabinet ministers are from the Commons, whilst junior ministers can be from either House. However, the Leader of the House of Lords must be a peer.

The Parliament of Great Britain was formed in 1707 following the ratification of the Treaty of Union by Acts of Union passed by the Parliament of England and the Parliament of Scotland, both Acts of Union stating, "That the United Kingdom of Great Britain be represented by one and the same Parliament to be styled The Parliament of Great Britain". At the start of the 19th century, Parliament was further enlarged by Acts of Union ratified by the Parliament of Great Britain and the Parliament of Ireland that abolished the latter and added 100 Irish MPs and 32 Lords to the former to create the Parliament of the United Kingdom of Great Britain and Ireland. The Royal and Parliamentary Titles Act 1927 formally amended the name to the "Parliament of the United Kingdom of Great Britain and Northern Ireland",[9] five years after the secession of the Irish Free State in 1922.

With the global expansion of the British Empire, the UK Parliament has shaped the political systems of many countries as ex-colonies and so it has been called the "Mother of Parliaments".[10] However, John Bright – who coined the epithet – used it in reference to the political culture of "England" rather than just the parliamentary system.[11]

In theory, the UK's supreme legislative power is officially vested in the Crown-in-Parliament. However, the Crown normally acts on the advice of the Prime Minister and the powers of the House of Lords are limited to only delaying legislation; thus power is de facto vested in the House of Commons.`,
	},
	{
		ID:   19,
		Name: "European Union",
		Content: `The European Union (EU) is a political and economic union of 28 member states that are located primarily in Europe.[12] It has an area of 4,475,757 km2 (1,728,099 sq mi) and an estimated population of about 513 million. The EU has developed an internal single market through a standardised system of laws that apply in all member states in those matters, and only those matters, where members have agreed to act as one. EU policies aim to ensure the free movement of people, goods, services and capital within the internal market,[13] enact legislation in justice and home affairs and maintain common policies on trade,[14] agriculture,[15] fisheries and regional development.[16] For travel within the Schengen Area, passport controls have been abolished.[17] A monetary union was established in 1999 and came into full force in 2002 and is composed of 19 EU member states which use the euro currency.

The EU and European citizenship were established when the Maastricht Treaty came into force in 1993.[18] The EU traces its origins to the European Coal and Steel Community (ECSC) and the European Economic Community (EEC), established, respectively, by the 1951 Treaty of Paris and 1957 Treaty of Rome. The original members of what came to be known as the European Communities were the Inner Six: Belgium, France, Italy, Luxembourg, the Netherlands, and West Germany. The Communities and its successors have grown in size by the accession of new member states and in power by the addition of policy areas to its remit. The latest major amendment to the constitutional basis of the EU, the Treaty of Lisbon, came into force in 2009. While no member state has left the EU or its antecedent organisations, the United Kingdom signified the intention to leave after a membership referendum in June 2016 and is negotiating its withdrawal.

Covering 7.3% of the world population,[19] the EU in 2017 generated a nominal gross domestic product (GDP) of 19.670 trillion US dollars, constituting approximately 24.6% of global nominal GDP.[20] Additionally, all 28 EU countries have a very high Human Development Index, according to the United Nations Development Programme. In 2012, the EU was awarded the Nobel Peace Prize.[21] Through the Common Foreign and Security Policy, the EU has developed a role in external relations and defence. The union maintains permanent diplomatic missions throughout the world and represents itself at the United Nations, the World Trade Organization, the G7 and the G20. Because of its global influence, the European Union has been described as an emerging superpower.[22]`,
	},
	{
		ID:   20,
		Name: "Germany",
		Content: `Germany (German: Deutschland German pronunciation: [ˈdɔʏtʃlant]), officially the Federal Republic of Germany (German: Bundesrepublik Deutschland, About this soundlisten (help·info)),[g] is a country in Central and Western Europe, lying between the Baltic and North Seas to the north, and the Alps, Lake Constance and the High Rhine to the south. It borders Denmark to the north, Poland and the Czech Republic to the east, Austria and Switzerland to the south, France to the southwest, and Luxembourg, Belgium and the Netherlands to the west.

Germany includes 16 constituent states, covers an area of 357,386 square kilometres (137,988 sq mi),[6] and has a largely temperate seasonal climate. With 83 million inhabitants, it is the second most populous state of Europe after Russia, the most populous state lying entirely in Europe, as well as the most populous member state of the European Union. Germany is a very decentralized country. Its capital and largest metropolis is Berlin, while Frankfurt serves as its financial capital and has the country's busiest airport. Germany's largest urban area is the Ruhr, with its main centres of Dortmund and Essen. The country's other major cities are Hamburg, Munich, Cologne, Stuttgart, Düsseldorf, Leipzig, Dresden, Bremen, Hannover, and Nuremberg.

Various Germanic tribes have inhabited the northern parts of modern Germany since classical antiquity. A region named Germania was documented before 100 AD. During the Migration Period, the Germanic tribes expanded southward. Beginning in the 10th century, German territories formed a central part of the Holy Roman Empire.[12] During the 16th century, northern German regions became the centre of the Protestant Reformation. After the collapse of the Holy Roman Empire, the German Confederation was formed in 1815. The German revolutions of 1848–49 resulted in the Frankfurt Parliament establishing major democratic rights.

In 1871, Germany became a nation state when most of the German states (most notably excluding Switzerland and Austria) unified into the Prussian-dominated German Empire. After World War I and the revolution of 1918–19, the Empire was replaced by the parliamentary Weimar Republic. The Nazi seizure of power in 1933 led to the establishment of a dictatorship, the annexation of Austria, World War II, and the Holocaust. After the end of World War II in Europe and a period of Allied occupation, Austria was re-established as an independent country and two new German states were founded: West Germany, formed from the American, British, and French occupation zones, and East Germany, formed from the Soviet occupation zone. Following the Revolutions of 1989 that ended communist rule in Central and Eastern Europe, the country was reunified on 3 October 1990.[13]

Today, the sovereign state of Germany is a federal parliamentary republic led by a chancellor. It is a great power with a strong economy; it has the world's fourth-largest economy by nominal GDP, and the fifth-largest by PPP. As a global leader in several industrial and technological sectors, it is both the world's third-largest exporter and importer of goods. As a developed country with a very high standard of living, it upholds a social security and universal health care system, environmental protection, and a tuition-free university education.

The Federal Republic of Germany was a founding member of the European Economic Community in 1957 and the European Union in 1993. It is part of the Schengen Area and became a co-founder of the Eurozone in 1999. Germany is a member of the United Nations, NATO, the G7, the G20, and the OECD. Known for its rich cultural history, Germany has been continuously the home of influential and successful artists, philosophers, musicians, film people, sportspeople, entrepreneurs, scientists, engineers, and inventors. Germany has a large number of World Heritage sites and is among the top tourism destinations in the world.`,
	},
	{
		ID:   21,
		Name: "Prime Minister",
		Content: `A Prime Minister is the head of a cabinet and the leader of the ministers in the executive branch of government, often in a parliamentary or semi-presidential system. A prime minister is not a head of state or chief executive officer of their respective nation, rather they are a head of government, serving typically under a monarch in a hybrid of aristocratic and democratic government forms.

In parliamentary systems fashioned after the Westminster system, the prime minister is the presiding and actual head of government and head of the executive branch. In such systems, the head of state or the head of state's official representative (often the monarch, president, or governor-general) usually holds a largely ceremonial position, although often with reserve powers.

In many systems, the prime minister selects and may dismiss other members of the cabinet, and allocates posts to members within the government. In most systems, the prime minister is the presiding member and chairman of the cabinet. In a minority of systems, notably in semi-presidential systems of government, a prime minister is the official who is appointed to manage the civil service and execute the directives of the head of state.

The prime minister is often, but not always, a member of the Legislature or the Lower House thereof and is expected with other ministers to ensure the passage of bills through the legislature. In some monarchies the monarch may also exercise executive powers (known as the royal prerogative) that are constitutionally vested in the crown and may be exercised without the approval of parliament.

As well as being head of government, a prime minister may have other roles or posts—the Prime Minister of the United Kingdom, for example, is also First Lord of the Treasury and Minister for the Civil Service.[1] Prime ministers may take other ministerial posts. For example, during the Second World War, Winston Churchill was also Minister of Defence (although there was then no Ministry of Defence) and in the current cabinet of Israel, Benjamin Netanyahu at one point served as Minister of Communications, Foreign Affairs, Regional Cooperation, Economy, Defense and Interior.`,
	},
	{
		ID:   22,
		Name: "Donald Trump",
		Content: `Donald John Trump (born June 14, 1946) is the 45th and current president of the United States. Before entering politics, he was a businessman and television personality.

Trump was born and raised in the New York City borough of Queens and received an economics degree from the Wharton School. He was appointed president of his family's real estate business in 1971, renamed it The Trump Organization, and expanded it from Queens and Brooklyn into Manhattan. The company built or renovated skyscrapers, hotels, casinos, and golf courses. Trump later started various side ventures, including licensing his name for real estate and consumer products. He managed the company until his 2017 inauguration. He co-authored several books, including The Art of the Deal. He owned the Miss Universe and Miss USA beauty pageants from 1996 to 2015, and he produced and hosted The Apprentice, a reality television show, from 2003 to 2015. Forbes estimates his net worth to be $3.1 billion.

Trump entered the 2016 presidential race as a Republican and defeated sixteen opponents in the primaries. His campaign received extensive free media coverage. Commentators described his political positions as populist, protectionist, and nationalist. Trump has made many false or misleading statements during his campaign and presidency. The statements have been documented by fact-checkers, and the media have widely described the phenomenon as unprecedented in American politics. Trump was elected president in a surprise victory over Democratic nominee Hillary Clinton. He became the oldest and wealthiest person ever to assume the presidency, the first without prior military or government service, and the fifth to have won the election despite having lost the popular vote.[b] His election and policies have sparked numerous protests. Many of his comments and actions have been perceived as racially charged or racist.

During his presidency, Trump ordered a travel ban on citizens from several Muslim-majority countries, citing security concerns; after legal challenges, the Supreme Court upheld the policy's third revision. He enacted a tax cut package for individuals and businesses, which also rescinded the individual health insurance mandate and allowed oil drilling in the Arctic Refuge. He partially repealed the Dodd-Frank Act that had imposed stricter constraints on banks in the aftermath of the 2008 financial crisis. In foreign policy, Trump pursued his America First agenda, withdrawing the U.S. from the Trans-Pacific Partnership trade negotiations, the Paris Agreement on climate change, and the Iran nuclear deal. He recognized Jerusalem as the capital of Israel, imposed import tariffs on various goods, triggering a trade war with China, and started negotiations with North Korea seeking denuclearization. Trump appointed Neil Gorsuch and Brett Kavanaugh to the Supreme Court.`,
	},
	{
		ID:   23,
		Name: "Concert",
		Content: `A concert is a live music performance in front of an audience. The performance may be by a single musician, sometimes then called a recital, or by a musical ensemble, such as an orchestra, choir, or band. Concerts are held in a wide variety and size of settings, from private houses and small nightclubs, dedicated concert halls, arenas and parks to large multipurpose buildings, and even sports stadiums. Indoor concerts held in the largest venues are sometimes called arena concerts or amphitheatre concerts. Informal names for a concert include show and gig.

Regardless of the venue, musicians usually perform on a stage. Concerts often require live event support with professional audio equipment. Before recorded music, concerts provided the main opportunity to hear musicians play.`,
	},
	{
		ID:   24,
		Name: "Bach",
		Content: `Johann Sebastian Bach[a] (31 March [O.S. 21 March] 1685 – 28 July 1750) was a German composer and musician of the Baroque period. He is known for instrumental compositions such as the Art of Fugue, the Brandenburg Concertos, and the Goldberg Variations as well as for vocal music such as the St Matthew Passion and the Mass in B minor. Since the 19th-century Bach Revival he has been generally regarded as one of the greatest composers of all time.[3]

The Bach family already counted several composers when Johann Sebastian was born as the last child of a city musician in Eisenach. After becoming an orphan at age 10, he lived for five years with his eldest brother Johann Christoph Bach, after which he continued his musical development in Lüneburg. From 1703 he was back in Thuringia, working as a musician for Protestant churches in Arnstadt and Mühlhausen and, for longer stretches of time, at courts in Weimar—where he expanded his repertoire for the organ—and Köthen—where he was mostly engaged with chamber music. From 1723 he was employed as Thomaskantor (cantor at St. Thomas) in Leipzig. He composed music for the principal Lutheran churches of the city, and for its university's student ensemble Collegium Musicum. From 1726 he published some of his keyboard and organ music. In Leipzig, as had happened in some of his earlier positions, he had a difficult relation with his employer, a situation that was little remedied when he was granted the title of court composer by King Augustus III of Poland in 1736. In the last decades of his life he reworked and extended many of his earlier compositions. He died of complications after eye surgery in 1750 at the age of 65.

Bach enriched established German styles through his mastery of counterpoint, harmonic and motivic organisation, and his adaptation of rhythms, forms, and textures from abroad, particularly from Italy and France. Bach's compositions include hundreds of cantatas, both sacred and secular.[4] He composed Latin church music, Passions, oratorios, and motets. He often adopted Lutheran hymns, not only in his larger vocal works, but for instance also in his four-part chorales and his sacred songs. He wrote extensively for organ and for other keyboard instruments. He composed concertos, for instance for violin and for harpsichord, and suites, as chamber music as well as for orchestra. Many of his works employ the genres of canon and fugue.

Throughout the 18th century Bach was mostly renowned as an organist, while his keyboard music, such as The Well-Tempered Clavier, was appreciated for its didactic qualities. The 19th century saw the publication of some major Bach biographies, and by the end of that century all of his known music had been printed. Dissemination of scholarship on the composer continued through periodicals and websites exclusively devoted to him, and other publications such as the Bach-Werke-Verzeichnis (BWV, a numbered catalogue of his works) and new critical editions of his compositions. His music was further popularised through a multitude of arrangements, including for instance the Air on the G String, and of recordings, for instance three different box sets with complete performances of the composer's works marking the 250th anniversary of his death.`,
	},
	{
		ID:   25,
		Name: "Orchestra",
		Content: `An orchestra (/ˈɔːrkɪstrə/; Italian: [orˈkɛstra]) is a large instrumental ensemble typical of classical music, which combines instruments from different families, including bowed string instruments such as the violin, viola, cello, and double bass, brass instruments such as the horn, trumpet, trombone and tuba, woodwinds such as the flute, oboe, clarinet and bassoon, and percussion instruments such as the timpani, bass drum, triangle, snare drum and cymbals, each grouped in sections. Other instruments such as the piano and celesta may sometimes appear in a fifth keyboard section or may stand alone, as may the concert harp and, for performances of some modern compositions, electronic instruments.

A full-size orchestra may sometimes be called a symphony orchestra or philharmonic orchestra. The actual number of musicians employed in a given performance may vary from seventy to over one hundred musicians, depending on the work being played and the size of the venue. The term chamber orchestra (and sometimes concert orchestra) usually refers to smaller-sized ensembles of about fifty musicians or fewer.[citation needed] Orchestras that specialize in the Baroque music of, for example, Johann Sebastian Bach and George Frideric Handel, or Classical repertoire, such as that of Haydn and Mozart, tend to be smaller than orchestras performing a Romantic music repertoire,[citation needed] such as the symphonies of Johannes Brahms. The typical orchestra grew in size throughout the 18th and 19th centuries, reaching a peak with the large orchestras (of as many as 120 players) called for in the works of Richard Wagner, and later, Gustav Mahler.

Orchestras are usually led by a conductor who directs the performance with movements of the hands and arms, often made easier for the musicians to see by use of a conductor's baton. The conductor unifies the orchestra, sets the tempo and shapes the sound of the ensemble.[1] The conductor also prepares the orchestra by leading rehearsals before the public concert, in which the conductor provides instructions to the musicians on their interpretation of the music being performed.

The leader of the first violin section, commonly called the concertmaster, also plays an important role in leading the musicians. In the Baroque music era (1600–1750), orchestras were often led by the concertmaster or by a chord-playing musician performing the basso continuo parts on a harpsichord or pipe organ, a tradition that some 20th century and 21st century early music ensembles continue. Orchestras play a wide range of repertoire, including symphonies, opera and ballet overtures, concertos for solo instruments, and as pit ensembles for operas, ballets, and some types of musical theatre (e.g., Gilbert and Sullivan operettas).

Amateur orchestras include those made up of students from an elementary school or a high school, youth orchestras, and community orchestras; the latter two typically being made up of amateur musicians from a particular city or region.

The term orchestra derives from the Greek ὀρχήστρα (orchestra), the name for the area in front of a stage in ancient Greek theatre reserved for the Greek chorus.[2]`,
	},
	{
		ID:   26,
		Name: "Pink Floyd",
		Content: `Pink Floyd were an English rock band formed in London in 1965. They achieved international acclaim with their progressive and psychedelic music. Distinguished by their philosophical lyrics, sonic experimentation, extended compositions, and elaborate live shows, they are one of the most commercially successful and influential groups in popular music history.

Pink Floyd were founded by students Syd Barrett on guitar and lead vocals, Nick Mason on drums, Roger Waters on bass and vocals, and Richard Wright on keyboards and vocals. They gained popularity performing in London's underground music scene during the late 1960s, and under Barrett's leadership released two charting singles and a successful debut album, The Piper at the Gates of Dawn (1967). Guitarist and vocalist David Gilmour joined in December 1967; Barrett left in April 1968 due to deteriorating mental health. Waters became the primary lyricist and conceptual leader, devising the concepts behind their albums The Dark Side of the Moon (1973), Wish You Were Here (1975), Animals (1977), The Wall (1979) and The Final Cut (1983). The Dark Side of the Moon and The Wall became two of the best-selling albums of all time.

Following creative tensions, Wright left Pink Floyd in 1979, followed by Waters in 1985. Gilmour and Mason continued as Pink Floyd, joined later by Wright. The three produced two more albums—A Momentary Lapse of Reason (1987) and The Division Bell (1994)—and toured through 1994. In 2005, after nearly two decades of enmity, Gilmour, Wright, Mason and Waters reunited as part of the global awareness event Live 8; Gilmour and Waters stated they had no further plans to reunite the band. Barrett died in 2006, and Wright in 2008. The last Pink Floyd studio album, The Endless River (2014), was recorded without Waters and based almost entirely on unreleased material from The Division Bell recording sessions.

Pink Floyd were inducted into the American Rock and Roll Hall of Fame in 1996 and the UK Music Hall of Fame in 2005. By 2013, they had sold more than 250 million records worldwide.`,
	},
	{
		ID:   27,
		Name: "Mixing Console",
		Content: `In sound recording and reproduction, and sound reinforcement systems, a mixing console is an electronic device for combining sounds of many different audio signals. Inputs to the console include microphones being used by singers and for picking up acoustic instruments, signals from electric or electronic instruments, or recorded music. Depending on the type, a mixer is able to control analog or digital signals. The modified signals are summed to produce the combined output signals, which can then be broadcast, amplified through a sound reinforcement system or recorded.

Mixing consoles are used in many applications, including recording studios, public address systems, sound reinforcement systems, nightclubs, broadcasting, television, and film post-production. A typical, simple application combines signals from microphones on stage into an amplifier that drives one set of loudspeakers for the audience. A DJ mixer may have only two channels, for mixing two record players. A coffeehouse's tiny stage might only have a six channel mixer, enough for two singer-guitarists and a percussionist. A nightclub stage's mixer for rock music shows may have 24 channels for mixing the signals from a rhythm section, lead guitar and several vocalists. A mixing console in a professional recording studio may have as many as 96 channels.[1]

In practice, mixers do more than simply mix signals. They can provide phantom power for condenser microphones; pan control, which changes a sound's apparent position in the stereo soundfield; filtering and equalization, which enables sound engineers to boost or cut selected frequencies to improve the sound; dynamic range compression, which allows engineers to increase the overall gain of the system or channel without exceeding the dynamic limits of the system; routing facilities, to send the signal from the mixer to another device, such as a sound recording system or a control room; and monitoring facilities, whereby one of a number of sources can be routed to loudspeakers or headphones for listening, often without affecting the mixer's main output.[2] Some mixers have onboard electronic effects, such as reverb. Some mixers intended for small venue live performance applications may include an integrated power amplifier.`,
	},
	{
		ID:   28,
		Name: "Apple Computers",
		Content: `Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook.[6][7]

The company's hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, and the HomePod smart speaker. Apple's software includes the macOS and iOS operating systems, the iTunes media player, the Safari web browser, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.

Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in April 1976 to develop and sell Wozniak's Apple I personal computer, though Wayne sold his share back within 12 days. It was incorporated as Apple Computer, Inc., in January 1977, and sales of its computers, including the Apple II, grew quickly. Within a few years, Jobs and Wozniak had hired a staff of computer designers and had a production line. Apple went public in 1980 to instant financial success. Over the next few years, Apple shipped new computers featuring innovative graphical user interfaces, such as the original Macintosh in 1984, and Apple's marketing advertisements for its products received widespread critical acclaim. However, the high price of its products and limited application library caused problems, as did power struggles between executives. In 1985, Wozniak departed Apple amicably and remained an honorary employee,[8] while Jobs and others resigned to found NeXT.[9]

As the market for personal computers expanded and evolved through the 1990s, Apple lost market share to the lower-priced duopoly of Microsoft Windows on Intel PC clones. The board recruited CEO Gil Amelio to what would be a 500-day charge for him to rehabilitate the financially troubled company—reshaping it with layoffs, executive restructuring, and product focus. In 1997, he led Apple to buy NeXT, solving the desperately failed operating system strategy and bringing Jobs back. Jobs pensively regained leadership status, becoming CEO in 2000. Apple swiftly returned to profitability under the revitalizing Think different campaign, as he rebuilt Apple's status by launching the iMac in 1998, opening the retail chain of Apple Stores in 2001, and acquiring numerous companies to broaden the software portfolio. In January 2007, Jobs renamed the company Apple Inc., reflecting its shifted focus toward consumer electronics, and launched the iPhone to great critical acclaim and financial success. In August 2011, Jobs resigned as CEO due to health complications, and Tim Cook became the new CEO. Two months later, Jobs died, marking the end of an era for the company.

Apple is well known for its size and revenues. Its worldwide annual revenue totaled $265 billion for the 2018 fiscal year. Apple is the world's largest information technology company by revenue and the world's third-largest mobile phone manufacturer after Samsung and Huawei.[10] In August 2018, Apple became the first public U.S. company to be valued at over $1 trillion.[11][12] The company employs 123,000 full-time employees[13] and maintains 504 retail stores in 24 countries as of 2018.[14] It operates the iTunes Store, which is the world's largest music retailer. As of January 2018, more than 1.3 billion Apple products are actively in use worldwide.[15] The company also has a high level of brand loyalty and is ranked as the world's most valuable brand. However, Apple receives significant criticism regarding the labor practices of its contractors, its environmental practices and unethical business practices, including anti-competitive behavior, as well as the origins of source materials.`,
	},
	{
		ID:   29,
		Name: "Uncle Bob",
		Content: `Robert C. Martin, colloquially known as "Uncle Bob",[2] is an American software engineer and instructor. He is best known for being one of the authors of the Agile Manifesto[3][4] and for developing several software design principles. He was also the editor-in-chief of C++ Report magazine and served as the first chairman of the Agile Alliance.

Martin operated the now-defunct company, Object Mentor, which provided instructor-led training courses about extreme programming methodology. He now operates two companies: Uncle Bob Consulting, which provides consulting and training services, and Clean Coders, which provides training videos.`,
	},
	{
		ID:   30,
		Name: "Golang",
		Content: `Go (also referred to as Golang[14]) is a statically typed, compiled programming language designed at Google[15] by Robert Griesemer, Rob Pike, and Ken Thompson.[12] Go is syntactically similar to C, but with memory safety, garbage collection, structural typing,[6] and CSP-style concurrency.[16]

There are two major implementations:

Google's self-hosting[17] compiler toolchain targeting multiple operating systems, mobile devices,[18] and WebAssembly.[19]
gccgo, a GCC frontend.[20][21]
A third compiler, GopherJS,[22] compiles Go to JavaScript for front-end web development.`,
	},
	{
		ID:   31,
		Name: "Google",
		Content: `Google LLC[5] is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, search engine, cloud computing, software, and hardware. It is considered one of the Big Four technology companies, alongside Amazon, Apple and Facebook.[6][7]

Google was founded in 1998 by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University in California. Together they own about 14 percent of its shares and control 56 percent of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998. An initial public offering (IPO) took place on August 19, 2004, and Google moved to its headquarters in Mountain View, California, nicknamed the Googleplex. In August 2015, Google announced plans to reorganize its various interests as a conglomerate called Alphabet Inc. Google is Alphabet's leading subsidiary and will continue to be the umbrella company for Alphabet's Internet interests. Sundar Pichai was appointed CEO of Google, replacing Larry Page who became the CEO of Alphabet.

The company's rapid growth since incorporation has triggered a chain of products, acquisitions, and partnerships beyond Google's core search engine (Google Search). It offers services designed for work and productivity (Google Docs, Google Sheets, and Google Slides), email (Gmail/Inbox), scheduling and time management (Google Calendar), cloud storage (Google Drive), instant messaging and video chat (Google Allo, Duo, Hangouts), language translation (Google Translate), mapping and navigation (Google Maps, Waze, Google Earth, Street View), video sharing (YouTube), note-taking (Google Keep), and photo organizing and editing (Google Photos). The company leads the development of the Android mobile operating system, the Google Chrome web browser, and Chrome OS, a lightweight operating system based on the Chrome browser. Google has moved increasingly into hardware; from 2010 to 2015, it partnered with major electronics manufacturers in the production of its Nexus devices, and it released multiple hardware products in October 2016, including the Google Pixel smartphone, Google Home smart speaker, Google Wifi mesh wireless router, and Google Daydream virtual reality headset. Google has also experimented with becoming an Internet carrier (Google Fiber, Project Fi, and Google Station).[8]

Google.com is the most visited website in the world.[9] Several other Google services also figure in the top 100 most visited websites, including YouTube and Blogger. Google is the most valuable brand in the world as of 2017,[10] but has received significant criticism involving issues such as privacy concerns, tax avoidance, antitrust, censorship, and search neutrality. Google's mission statement is "to organize the world's information and make it universally accessible and useful". The companies unofficial slogan "Don't be evil" was removed from the company's code of conduct around May 2018.[11][12]`,
	},
	{
		ID:   32,
		Name: "Hitchhikers Guide to the Galaxy",
		Content: `The Hitchhiker's Guide to the Galaxy[1] (sometimes referred to as HG2G,[2] HHGTTG,[3] H2G2,[4] or tHGttG) is a comedy science fiction series created by Douglas Adams. Originally a radio comedy broadcast on BBC Radio 4 in 1978, it was later adapted to other formats, including stage shows, novels, comic books, a 1981 TV series, a 1984 video game, and 2005 feature film.

A prominent series in British popular culture, The Hitchhiker's Guide to the Galaxy has become an international multi-media phenomenon; the novels are the most widely distributed, having been translated into more than 30 languages by 2005.[5][6] In 2017, BBC Radio 4 announced a 40th-anniversary celebration with Dirk Maggs, one of the original producers, in charge.[7] This sixth series of the sci-fi spoof has been based on Eoin Colfer's book And Another Thing, with additional unpublished material by Douglas Adams. The first of six new episodes was broadcast on 8 March 2018.[8]

The broad narrative of Hitchhiker follows the misadventures of the last surviving man, Arthur Dent, following the demolition of the planet Earth by a Vogon constructor fleet to make way for a hyperspace bypass. Dent is rescued from Earth's destruction by Ford Prefect—a human-like alien writer for the eccentric, electronic travel guide The Hitchhiker's Guide to the Galaxy—by hitchhiking onto a passing Vogon spacecraft. Following his rescue, Dent explores the galaxy with Prefect and encounters Trillian, another human who had been taken from Earth (prior to its destruction) by the two-headed President of the Galaxy Zaphod Beeblebrox and the depressed Marvin, the Paranoid Android. Certain narrative details were changed between the various adaptations.`,
	},
	{
		ID:   33,
		Name: "Bible",
		Content: `The Bible (from Koine Greek τὰ βιβλία, tà biblía, "the books")[1][a] is a collection of sacred texts or scriptures. Varying parts of the Bible are considered to be a product of divine inspiration and a record of the relationship between God and humans by Christians, Jews, Samaritans, and Rastafarians.

What is regarded as canonical text differs depending on traditions and groups; a number of Bible canons have evolved, with overlapping and diverging contents.[2] The Hebrew Bible overlaps with the Greek Septuagint and the Christian Old Testament. The Christian New Testament is a collection of writings by early Christians, believed to be mostly Jewish disciples of Christ, written in first-century Koine Greek. Among Christian denominations there is some disagreement about what should be included in the canon, primarily about the Apocrypha, a list of works that are regarded with varying levels of respect.

Attitudes towards the Bible also differ among Christian groups. Roman Catholics, high church Anglicans and Eastern Orthodox Christians stress the harmony and importance of the Bible and sacred tradition, while Protestant churches, including Evangelical Anglicans, focus on the idea of sola scriptura, or scripture alone. This concept arose during the Protestant Reformation, and many denominations today support the use of the Bible as the only infallible source of Christian teaching.

The Bible has been a massive influence on literature and history, especially in the Western World, where the Gutenberg Bible was the first book printed using movable type.[3] According to the March 2007 edition of Time, the Bible "has done more to shape literature, history, entertainment, and culture than any book ever written. Its influence on world history is unparalleled, and shows no signs of abating."[3] With estimated total sales of over 5 billion copies, it is widely considered to be the most influential and best-selling book of all time.[3][4][5][6] As of the 2000s, it sells approximately 100 million copies annually.[7][8]`,
	},
	{
		ID:   34,
		Name: "Quran",
		Content: `The Quran (/kɔːrˈɑːn/[a] kor-AHN; Arabic: القرآن‎, translit. al-Qurʾān Arabic pronunciation: [alqur'ʔaːn],[b] literally meaning "the recitation"; also romanized Qur'an or Koran[c]) is the central religious text of Islam, which Muslims believe to be a revelation from God (Allah).[1] It is widely regarded as the finest work in classical Arabic literature.[2][3][4][5] The Quran is divided into chapters (Arabic: سورة sūrah, plural سور suwar), which are subdivided into verses (Arabic: آية āyah, plural آيات āyāt).

Muslims believe that the Quran was orally revealed by God to the final Prophet, Muhammad, through the archangel Gabriel (Jibril),[6][7] incrementally over a period of some 23 years, beginning on 22 December 609 CE,[8] when Muhammad was 40, and concluding in 632, the year of his death.[1][9][10] Muslims regard the Quran as Muhammad's most important miracle, a proof of his prophethood,[11] and the culmination of a series of divine messages starting with those revealed to Adam and ending with Muhammad. The word "Quran" occurs some 70 times in the Quran's text, and other names and words are also said to refer to the Quran.[12]

According to tradition, several of Muhammad's companions served as scribes and recorded the revelations.[13] Shortly after his death, the Quran was compiled by the companions, who had written down or memorized parts of it.[14] The codices showed differences that motivated Caliph Uthman to establish a standard version, now known as Uthman's codex, which is generally considered the archetype of the Quran known today. There are, however, variant readings, with mostly minor differences in meaning.[13]

The Quran assumes familiarity with major narratives recounted in the Biblical scriptures. It summarizes some, dwells at length on others and, in some cases, presents alternative accounts and interpretations of events.[15][16][17] The Quran describes itself as a book of guidance for mankind 2:185. It sometimes offers detailed accounts of specific historical events, and it often emphasizes the moral significance of an event over its narrative sequence.[18][19] Hadith are additional oral and written traditions supplementing the Quran; from careful authentication they are believed to describe words and actions of Muhammad, and in some traditions also those closest to him.[20] In most denominations of Islam, the Quran is used together with hadith to interpret sharia (Islamic) law;[20] in a small number of denominations, only the Quran is used as a source, an approach called Quranism. During prayers, the Quran is recited only in Arabic.[21]

Someone who has memorized the entire Quran is called a hafiz. Quranic verse (ayah) is sometimes recited with a special kind of elocution reserved for this purpose, called tajwid. During the month of Ramadan, Muslims typically complete the recitation of the whole Quran during tarawih prayers. In order to extrapolate the meaning of a particular Quranic verse, most Muslims rely on exegesis, or tafsir.[22]`,
	},
	{
		ID:   35,
		Name: "Fifty shades of grey",
		Content: `Fifty Shades of Grey is a 2011 erotic romance novel by British author E. L. James.[1] It became the first instalment in the Fifty Shades novel series that traces the deepening relationship between a college graduate, Anastasia Steele, and a young business magnate, Christian Grey. It is notable for its explicitly erotic scenes featuring elements of sexual practices involving BDSM (bondage/discipline, dominance/submission, and sadism/masochism). Originally self-published as an ebook and print-on-demand, the publishing rights to the novel were acquired by Vintage Books in March 2012.

Fifty Shades of Grey has topped best-seller lists around the world, selling over 125 million copies worldwide by June 2015. It has been translated into 52 languages, and set a record in the United Kingdom as the fastest-selling paperback of all time. Critical reception of the book, however, has tended towards the negative, with the quality of its prose generally seen as poor. Universal Pictures and Focus Features produced a film adaptation, which was released on 13 February 2015,[2] and also received unfavourable reviews even though it was a box office success.

The second and third volumes of the original Fifty Shades trilogy, Fifty Shades Darker and Fifty Shades Freed, were published in 2012. Grey: Fifty Shades of Grey as Told by Christian, a version of Fifty Shades of Grey being told from Christian's point of view, was published in June 2015. Darker: Fifty Shades Darker as Told by Christian was the fifth book in the series, published in November 2017.`,
	},
}
