/*                          _       _
 *__      _____  __ ___   ___  __ _| |_ ___
 *\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
 * \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
 *  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
 *
 * Copyright © 2016 - 2019 Weaviate. All rights reserved.
 * LICENSE: https://github.com/creativesoftwarefdn/weaviate/blob/develop/LICENSE.md
 * DESIGN & CONCEPT: Bob van Luijt (@bobvanluijt)
 * CONTACT: hello@creativesoftwarefdn.org
 */ // Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Weaviate - Decentralised Knowledge Graph
Decentralised Knowledge Graph


    Schemes:
      https
    Host: localhost
    BasePath: /weaviate/v1
    Version: 0.12.46
    Contact: Weaviate<hello@creativesoftwarefdn.org> https://github.com/creativesoftwarefdn

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
