//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2023 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// WeaviateBaseOKCode is the HTTP code returned for type WeaviateBaseOK
const WeaviateBaseOKCode int = 200

/*
WeaviateBaseOK Weaviate is alive and ready to serve content

swagger:response weaviateBaseOK
*/
type WeaviateBaseOK struct {
}

// NewWeaviateBaseOK creates WeaviateBaseOK with default headers values
func NewWeaviateBaseOK() *WeaviateBaseOK {

	return &WeaviateBaseOK{}
}

// WriteResponse to the client
func (o *WeaviateBaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
