//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2019 Weaviate. All rights reserved.
//  LICENSE: https://github.com/semi-technologies/weaviate/blob/develop/LICENSE.md
//  DESIGN & CONCEPT: Bob van Luijt (@bobvanluijt)
//  CONTACT: hello@semi.technology
//

// Code generated by go-swagger; DO NOT EDIT.

package things

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/semi-technologies/weaviate/entities/models"
)

// WeaviateThingsCreateHandlerFunc turns a function with the right signature into a weaviate things create handler
type WeaviateThingsCreateHandlerFunc func(WeaviateThingsCreateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn WeaviateThingsCreateHandlerFunc) Handle(params WeaviateThingsCreateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// WeaviateThingsCreateHandler interface for that can handle valid weaviate things create params
type WeaviateThingsCreateHandler interface {
	Handle(WeaviateThingsCreateParams, *models.Principal) middleware.Responder
}

// NewWeaviateThingsCreate creates a new http.Handler for the weaviate things create operation
func NewWeaviateThingsCreate(ctx *middleware.Context, handler WeaviateThingsCreateHandler) *WeaviateThingsCreate {
	return &WeaviateThingsCreate{Context: ctx, Handler: handler}
}

/*WeaviateThingsCreate swagger:route POST /things things weaviateThingsCreate

Create a new Thing based on a Thing template.

Registers a new Thing. Given meta-data and schema values are validated.

*/
type WeaviateThingsCreate struct {
	Context *middleware.Context
	Handler WeaviateThingsCreateHandler
}

func (o *WeaviateThingsCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWeaviateThingsCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
