//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/weaviate/weaviate/entities/models"
)

// DeletePolicyNoContentCode is the HTTP code returned for type DeletePolicyNoContent
const DeletePolicyNoContentCode int = 204

/*
DeletePolicyNoContent Successfully deleted.

swagger:response deletePolicyNoContent
*/
type DeletePolicyNoContent struct {
}

// NewDeletePolicyNoContent creates DeletePolicyNoContent with default headers values
func NewDeletePolicyNoContent() *DeletePolicyNoContent {

	return &DeletePolicyNoContent{}
}

// WriteResponse to the client
func (o *DeletePolicyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeletePolicyBadRequestCode is the HTTP code returned for type DeletePolicyBadRequest
const DeletePolicyBadRequestCode int = 400

/*
DeletePolicyBadRequest Bad request

swagger:response deletePolicyBadRequest
*/
type DeletePolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeletePolicyBadRequest creates DeletePolicyBadRequest with default headers values
func NewDeletePolicyBadRequest() *DeletePolicyBadRequest {

	return &DeletePolicyBadRequest{}
}

// WithPayload adds the payload to the delete policy bad request response
func (o *DeletePolicyBadRequest) WithPayload(payload *models.ErrorResponse) *DeletePolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete policy bad request response
func (o *DeletePolicyBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePolicyUnauthorizedCode is the HTTP code returned for type DeletePolicyUnauthorized
const DeletePolicyUnauthorizedCode int = 401

/*
DeletePolicyUnauthorized Unauthorized or invalid credentials.

swagger:response deletePolicyUnauthorized
*/
type DeletePolicyUnauthorized struct {
}

// NewDeletePolicyUnauthorized creates DeletePolicyUnauthorized with default headers values
func NewDeletePolicyUnauthorized() *DeletePolicyUnauthorized {

	return &DeletePolicyUnauthorized{}
}

// WriteResponse to the client
func (o *DeletePolicyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeletePolicyForbiddenCode is the HTTP code returned for type DeletePolicyForbidden
const DeletePolicyForbiddenCode int = 403

/*
DeletePolicyForbidden Forbidden

swagger:response deletePolicyForbidden
*/
type DeletePolicyForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeletePolicyForbidden creates DeletePolicyForbidden with default headers values
func NewDeletePolicyForbidden() *DeletePolicyForbidden {

	return &DeletePolicyForbidden{}
}

// WithPayload adds the payload to the delete policy forbidden response
func (o *DeletePolicyForbidden) WithPayload(payload *models.ErrorResponse) *DeletePolicyForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete policy forbidden response
func (o *DeletePolicyForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePolicyForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePolicyInternalServerErrorCode is the HTTP code returned for type DeletePolicyInternalServerError
const DeletePolicyInternalServerErrorCode int = 500

/*
DeletePolicyInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response deletePolicyInternalServerError
*/
type DeletePolicyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeletePolicyInternalServerError creates DeletePolicyInternalServerError with default headers values
func NewDeletePolicyInternalServerError() *DeletePolicyInternalServerError {

	return &DeletePolicyInternalServerError{}
}

// WithPayload adds the payload to the delete policy internal server error response
func (o *DeletePolicyInternalServerError) WithPayload(payload *models.ErrorResponse) *DeletePolicyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete policy internal server error response
func (o *DeletePolicyInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePolicyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
