//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BackupConfig Backup custom configuration.
//
// swagger:model BackupConfig
type BackupConfig struct {

	// Name of the bucket, container, volume, etc.
	Bucket string `json:"Bucket,omitempty"`

	// Desired CPU core utilization ranging from 1%-80%
	// Maximum: 80
	// Minimum: 1
	CPUPercentage int64 `json:"CPUPercentage,omitempty"`

	// Deprecated, has no effect.
	ChunkSize int64 `json:"ChunkSize,omitempty"`

	// compression level used by compression algorithm
	// Enum: [DefaultCompression BestSpeed BestCompression ZstdDefaultCompression ZstdBestSpeed ZstdBestCompression NoCompression]
	CompressionLevel string `json:"CompressionLevel,omitempty"`

	// Name of the endpoint, e.g. s3.amazonaws.com.
	Endpoint string `json:"Endpoint,omitempty"`

	// Path or key within the bucket.
	Path string `json:"Path,omitempty"`

	// How long the coordinator waits for replica convergence proof before shards fall back to being archived by every replica. Only used when dedupeReplicas is set. The wait happens synchronously inside the backup creation request, which blocks for roughly 10 seconds plus up to this timeout; size client timeouts accordingly.
	// Maximum: 600
	// Minimum: 1
	DedupeConvergenceTimeoutSeconds int64 `json:"dedupeConvergenceTimeoutSeconds,omitempty"`

	// If true, shards of replicated collections that are provably in sync (via async-replication checkpoints) are archived by a single replica instead of every replica, and a restore copies them back to all replicas. Shards that cannot be proven in sync fall back to being archived by every replica. The proof is the one async replication itself uses (matching object UUIDs and update timestamps at a checkpoint), and the archived copy is the designated replica's state at archive time. Requires async replication on replicated collections and a cluster where every node supports this option; such backups can only be restored by versions that support it, and their restore requires every replica node of the archived sharding state to be resolvable (or mapped via node_mapping).
	DedupeReplicas bool `json:"dedupeReplicas,omitempty"`
}

// Validate validates this backup config
func (m *BackupConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUPercentage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompressionLevel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDedupeConvergenceTimeoutSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BackupConfig) validateCPUPercentage(formats strfmt.Registry) error {
	if swag.IsZero(m.CPUPercentage) { // not required
		return nil
	}

	if err := validate.MinimumInt("CPUPercentage", "body", m.CPUPercentage, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("CPUPercentage", "body", m.CPUPercentage, 80, false); err != nil {
		return err
	}

	return nil
}

var backupConfigTypeCompressionLevelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DefaultCompression","BestSpeed","BestCompression","ZstdDefaultCompression","ZstdBestSpeed","ZstdBestCompression","NoCompression"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		backupConfigTypeCompressionLevelPropEnum = append(backupConfigTypeCompressionLevelPropEnum, v)
	}
}

const (

	// BackupConfigCompressionLevelDefaultCompression captures enum value "DefaultCompression"
	BackupConfigCompressionLevelDefaultCompression string = "DefaultCompression"

	// BackupConfigCompressionLevelBestSpeed captures enum value "BestSpeed"
	BackupConfigCompressionLevelBestSpeed string = "BestSpeed"

	// BackupConfigCompressionLevelBestCompression captures enum value "BestCompression"
	BackupConfigCompressionLevelBestCompression string = "BestCompression"

	// BackupConfigCompressionLevelZstdDefaultCompression captures enum value "ZstdDefaultCompression"
	BackupConfigCompressionLevelZstdDefaultCompression string = "ZstdDefaultCompression"

	// BackupConfigCompressionLevelZstdBestSpeed captures enum value "ZstdBestSpeed"
	BackupConfigCompressionLevelZstdBestSpeed string = "ZstdBestSpeed"

	// BackupConfigCompressionLevelZstdBestCompression captures enum value "ZstdBestCompression"
	BackupConfigCompressionLevelZstdBestCompression string = "ZstdBestCompression"

	// BackupConfigCompressionLevelNoCompression captures enum value "NoCompression"
	BackupConfigCompressionLevelNoCompression string = "NoCompression"
)

// prop value enum
func (m *BackupConfig) validateCompressionLevelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, backupConfigTypeCompressionLevelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BackupConfig) validateCompressionLevel(formats strfmt.Registry) error {
	if swag.IsZero(m.CompressionLevel) { // not required
		return nil
	}

	// value enum
	if err := m.validateCompressionLevelEnum("CompressionLevel", "body", m.CompressionLevel); err != nil {
		return err
	}

	return nil
}

func (m *BackupConfig) validateDedupeConvergenceTimeoutSeconds(formats strfmt.Registry) error {
	if swag.IsZero(m.DedupeConvergenceTimeoutSeconds) { // not required
		return nil
	}

	if err := validate.MinimumInt("dedupeConvergenceTimeoutSeconds", "body", m.DedupeConvergenceTimeoutSeconds, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("dedupeConvergenceTimeoutSeconds", "body", m.DedupeConvergenceTimeoutSeconds, 600, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this backup config based on context it is used
func (m *BackupConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackupConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackupConfig) UnmarshalBinary(b []byte) error {
	var res BackupConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
