//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExportCreateRequest Request to create a new export operation
//
// swagger:model ExportCreateRequest
type ExportCreateRequest struct {

	// config
	Config *ExportCreateRequestConfig `json:"config,omitempty"`

	// List of collection names to exclude from the export. Cannot be used with 'include'.
	Exclude []string `json:"exclude"`

	// Output file format for the export.
	// Required: true
	// Enum: [parquet]
	FileFormat *string `json:"file_format"`

	// Unique identifier for this export. Must be URL-safe.
	// Required: true
	ID *string `json:"id"`

	// List of collection names to include in the export. Cannot be used with 'exclude'.
	Include []string `json:"include"`
}

// Validate validates this export create request
func (m *ExportCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExportCreateRequest) validateConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.Config) { // not required
		return nil
	}

	if m.Config != nil {
		if err := m.Config.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("config")
			}
			return err
		}
	}

	return nil
}

var exportCreateRequestTypeFileFormatPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["parquet"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		exportCreateRequestTypeFileFormatPropEnum = append(exportCreateRequestTypeFileFormatPropEnum, v)
	}
}

const (

	// ExportCreateRequestFileFormatParquet captures enum value "parquet"
	ExportCreateRequestFileFormatParquet string = "parquet"
)

// prop value enum
func (m *ExportCreateRequest) validateFileFormatEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, exportCreateRequestTypeFileFormatPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ExportCreateRequest) validateFileFormat(formats strfmt.Registry) error {

	if err := validate.Required("file_format", "body", m.FileFormat); err != nil {
		return err
	}

	// value enum
	if err := m.validateFileFormatEnum("file_format", "body", *m.FileFormat); err != nil {
		return err
	}

	return nil
}

func (m *ExportCreateRequest) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this export create request based on the context it is used
func (m *ExportCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExportCreateRequest) contextValidateConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.Config != nil {
		if err := m.Config.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExportCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExportCreateRequest) UnmarshalBinary(b []byte) error {
	var res ExportCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ExportCreateRequestConfig Backend-specific configuration
//
// swagger:model ExportCreateRequestConfig
type ExportCreateRequestConfig struct {

	// Bucket, container, or volume name for cloud storage backends
	Bucket string `json:"bucket,omitempty"`

	// Path prefix within the bucket or filesystem
	Path string `json:"path,omitempty"`
}

// Validate validates this export create request config
func (m *ExportCreateRequestConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this export create request config based on context it is used
func (m *ExportCreateRequestConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExportCreateRequestConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExportCreateRequestConfig) UnmarshalBinary(b []byte) error {
	var res ExportCreateRequestConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
