//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NamespaceUpdateRequest Update payload for an existing namespace.
//
// swagger:model NamespaceUpdateRequest
type NamespaceUpdateRequest struct {

	// Cluster node to use for future placements in this namespace. Must be a current storage candidate. Existing live shards are not moved.
	// Required: true
	HomeNode *string `json:"home_node"`
}

// Validate validates this namespace update request
func (m *NamespaceUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHomeNode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NamespaceUpdateRequest) validateHomeNode(formats strfmt.Registry) error {

	if err := validate.Required("home_node", "body", m.HomeNode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this namespace update request based on context it is used
func (m *NamespaceUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NamespaceUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NamespaceUpdateRequest) UnmarshalBinary(b []byte) error {
	var res NamespaceUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
