//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UsageLimitExceededResponse Returned with HTTP 429 when a configured Weaviate usage limit (objects/collections/tenants/shards) is exceeded. The structured fields (`errorCode`, `limit`, `value`) are stable contract; the `message` text is operator-overridable via the `USAGE_LIMITS_ERROR_MESSAGE` template.
//
// swagger:model UsageLimitExceededResponse
type UsageLimitExceededResponse struct {

	// Machine-stable identifier. Always `USAGE_LIMIT_EXCEEDED` for this response.
	// Enum: [USAGE_LIMIT_EXCEEDED]
	ErrorCode string `json:"errorCode,omitempty"`

	// Which limit was hit.
	// Enum: [objects collections tenants shards]
	Limit string `json:"limit,omitempty"`

	// Human-readable message rendered from the `USAGE_LIMITS_ERROR_MESSAGE` template with `{limit}` and `{value}` placeholders substituted.
	Message string `json:"message,omitempty"`

	// The configured threshold value (the cap, not the current count).
	Value int64 `json:"value,omitempty"`
}

// Validate validates this usage limit exceeded response
func (m *UsageLimitExceededResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrorCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var usageLimitExceededResponseTypeErrorCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["USAGE_LIMIT_EXCEEDED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		usageLimitExceededResponseTypeErrorCodePropEnum = append(usageLimitExceededResponseTypeErrorCodePropEnum, v)
	}
}

const (

	// UsageLimitExceededResponseErrorCodeUSAGELIMITEXCEEDED captures enum value "USAGE_LIMIT_EXCEEDED"
	UsageLimitExceededResponseErrorCodeUSAGELIMITEXCEEDED string = "USAGE_LIMIT_EXCEEDED"
)

// prop value enum
func (m *UsageLimitExceededResponse) validateErrorCodeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, usageLimitExceededResponseTypeErrorCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UsageLimitExceededResponse) validateErrorCode(formats strfmt.Registry) error {
	if swag.IsZero(m.ErrorCode) { // not required
		return nil
	}

	// value enum
	if err := m.validateErrorCodeEnum("errorCode", "body", m.ErrorCode); err != nil {
		return err
	}

	return nil
}

var usageLimitExceededResponseTypeLimitPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["objects","collections","tenants","shards"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		usageLimitExceededResponseTypeLimitPropEnum = append(usageLimitExceededResponseTypeLimitPropEnum, v)
	}
}

const (

	// UsageLimitExceededResponseLimitObjects captures enum value "objects"
	UsageLimitExceededResponseLimitObjects string = "objects"

	// UsageLimitExceededResponseLimitCollections captures enum value "collections"
	UsageLimitExceededResponseLimitCollections string = "collections"

	// UsageLimitExceededResponseLimitTenants captures enum value "tenants"
	UsageLimitExceededResponseLimitTenants string = "tenants"

	// UsageLimitExceededResponseLimitShards captures enum value "shards"
	UsageLimitExceededResponseLimitShards string = "shards"
)

// prop value enum
func (m *UsageLimitExceededResponse) validateLimitEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, usageLimitExceededResponseTypeLimitPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UsageLimitExceededResponse) validateLimit(formats strfmt.Registry) error {
	if swag.IsZero(m.Limit) { // not required
		return nil
	}

	// value enum
	if err := m.validateLimitEnum("limit", "body", m.Limit); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this usage limit exceeded response based on context it is used
func (m *UsageLimitExceededResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsageLimitExceededResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsageLimitExceededResponse) UnmarshalBinary(b []byte) error {
	var res UsageLimitExceededResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
