//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package tokenize

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/weaviate/weaviate/entities/models"
)

// TokenizeOKCode is the HTTP code returned for type TokenizeOK
const TokenizeOKCode int = 200

/*
TokenizeOK Successfully tokenized the text.

swagger:response tokenizeOK
*/
type TokenizeOK struct {

	/*
	  In: Body
	*/
	Payload *models.TokenizeResponse `json:"body,omitempty"`
}

// NewTokenizeOK creates TokenizeOK with default headers values
func NewTokenizeOK() *TokenizeOK {

	return &TokenizeOK{}
}

// WithPayload adds the payload to the tokenize o k response
func (o *TokenizeOK) WithPayload(payload *models.TokenizeResponse) *TokenizeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tokenize o k response
func (o *TokenizeOK) SetPayload(payload *models.TokenizeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TokenizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TokenizeBadRequestCode is the HTTP code returned for type TokenizeBadRequest
const TokenizeBadRequestCode int = 400

/*
TokenizeBadRequest Invalid request body, missing required fields, or unknown tokenization method.

swagger:response tokenizeBadRequest
*/
type TokenizeBadRequest struct {
}

// NewTokenizeBadRequest creates TokenizeBadRequest with default headers values
func NewTokenizeBadRequest() *TokenizeBadRequest {

	return &TokenizeBadRequest{}
}

// WriteResponse to the client
func (o *TokenizeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// TokenizeUnauthorizedCode is the HTTP code returned for type TokenizeUnauthorized
const TokenizeUnauthorizedCode int = 401

/*
TokenizeUnauthorized Unauthorized or invalid credentials.

swagger:response tokenizeUnauthorized
*/
type TokenizeUnauthorized struct {
}

// NewTokenizeUnauthorized creates TokenizeUnauthorized with default headers values
func NewTokenizeUnauthorized() *TokenizeUnauthorized {

	return &TokenizeUnauthorized{}
}

// WriteResponse to the client
func (o *TokenizeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// TokenizeForbiddenCode is the HTTP code returned for type TokenizeForbidden
const TokenizeForbiddenCode int = 403

/*
TokenizeForbidden Forbidden

swagger:response tokenizeForbidden
*/
type TokenizeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewTokenizeForbidden creates TokenizeForbidden with default headers values
func NewTokenizeForbidden() *TokenizeForbidden {

	return &TokenizeForbidden{}
}

// WithPayload adds the payload to the tokenize forbidden response
func (o *TokenizeForbidden) WithPayload(payload *models.ErrorResponse) *TokenizeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tokenize forbidden response
func (o *TokenizeForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TokenizeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
