//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package export

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/weaviate/weaviate/entities/models"
)

// ExportCancelNoContentCode is the HTTP code returned for type ExportCancelNoContent
const ExportCancelNoContentCode int = 204

/*
ExportCancelNoContent Export cancelled successfully.

swagger:response exportCancelNoContent
*/
type ExportCancelNoContent struct{}

// NewExportCancelNoContent creates ExportCancelNoContent with default headers values
func NewExportCancelNoContent() *ExportCancelNoContent {
	return &ExportCancelNoContent{}
}

// WriteResponse to the client
func (o *ExportCancelNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ExportCancelUnauthorizedCode is the HTTP code returned for type ExportCancelUnauthorized
const ExportCancelUnauthorizedCode int = 401

/*
ExportCancelUnauthorized Unauthorized or invalid credentials.

swagger:response exportCancelUnauthorized
*/
type ExportCancelUnauthorized struct{}

// NewExportCancelUnauthorized creates ExportCancelUnauthorized with default headers values
func NewExportCancelUnauthorized() *ExportCancelUnauthorized {
	return &ExportCancelUnauthorized{}
}

// WriteResponse to the client
func (o *ExportCancelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ExportCancelForbiddenCode is the HTTP code returned for type ExportCancelForbidden
const ExportCancelForbiddenCode int = 403

/*
ExportCancelForbidden Forbidden - insufficient permissions

swagger:response exportCancelForbidden
*/
type ExportCancelForbidden struct {
	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExportCancelForbidden creates ExportCancelForbidden with default headers values
func NewExportCancelForbidden() *ExportCancelForbidden {
	return &ExportCancelForbidden{}
}

// WithPayload adds the payload to the export cancel forbidden response
func (o *ExportCancelForbidden) WithPayload(payload *models.ErrorResponse) *ExportCancelForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export cancel forbidden response
func (o *ExportCancelForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportCancelForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportCancelNotFoundCode is the HTTP code returned for type ExportCancelNotFound
const ExportCancelNotFoundCode int = 404

/*
ExportCancelNotFound Export not found

swagger:response exportCancelNotFound
*/
type ExportCancelNotFound struct {
	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExportCancelNotFound creates ExportCancelNotFound with default headers values
func NewExportCancelNotFound() *ExportCancelNotFound {
	return &ExportCancelNotFound{}
}

// WithPayload adds the payload to the export cancel not found response
func (o *ExportCancelNotFound) WithPayload(payload *models.ErrorResponse) *ExportCancelNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export cancel not found response
func (o *ExportCancelNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportCancelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportCancelConflictCode is the HTTP code returned for type ExportCancelConflict
const ExportCancelConflictCode int = 409

/*
ExportCancelConflict Export has already finished and cannot be cancelled

swagger:response exportCancelConflict
*/
type ExportCancelConflict struct {
	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExportCancelConflict creates ExportCancelConflict with default headers values
func NewExportCancelConflict() *ExportCancelConflict {
	return &ExportCancelConflict{}
}

// WithPayload adds the payload to the export cancel conflict response
func (o *ExportCancelConflict) WithPayload(payload *models.ErrorResponse) *ExportCancelConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export cancel conflict response
func (o *ExportCancelConflict) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportCancelConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportCancelUnprocessableEntityCode is the HTTP code returned for type ExportCancelUnprocessableEntity
const ExportCancelUnprocessableEntityCode int = 422

/*
ExportCancelUnprocessableEntity Invalid request (e.g., unsupported backend)

swagger:response exportCancelUnprocessableEntity
*/
type ExportCancelUnprocessableEntity struct {
	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExportCancelUnprocessableEntity creates ExportCancelUnprocessableEntity with default headers values
func NewExportCancelUnprocessableEntity() *ExportCancelUnprocessableEntity {
	return &ExportCancelUnprocessableEntity{}
}

// WithPayload adds the payload to the export cancel unprocessable entity response
func (o *ExportCancelUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *ExportCancelUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export cancel unprocessable entity response
func (o *ExportCancelUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportCancelUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportCancelInternalServerErrorCode is the HTTP code returned for type ExportCancelInternalServerError
const ExportCancelInternalServerErrorCode int = 500

/*
ExportCancelInternalServerError Internal server error occurred while cancelling export

swagger:response exportCancelInternalServerError
*/
type ExportCancelInternalServerError struct {
	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExportCancelInternalServerError creates ExportCancelInternalServerError with default headers values
func NewExportCancelInternalServerError() *ExportCancelInternalServerError {
	return &ExportCancelInternalServerError{}
}

// WithPayload adds the payload to the export cancel internal server error response
func (o *ExportCancelInternalServerError) WithPayload(payload *models.ErrorResponse) *ExportCancelInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export cancel internal server error response
func (o *ExportCancelInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportCancelInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
