FROM python:3.10-slim

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip setuptools

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY fake_fvs.py .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["python fake_fvs.py 7761"]
