//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// NewSearchNearTextParams creates a new SearchNearTextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchNearTextParams() *SearchNearTextParams {
	return &SearchNearTextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchNearTextParamsWithTimeout creates a new SearchNearTextParams object
// with the ability to set a timeout on a request.
func NewSearchNearTextParamsWithTimeout(timeout time.Duration) *SearchNearTextParams {
	return &SearchNearTextParams{
		timeout: timeout,
	}
}

// NewSearchNearTextParamsWithContext creates a new SearchNearTextParams object
// with the ability to set a context for a request.
func NewSearchNearTextParamsWithContext(ctx context.Context) *SearchNearTextParams {
	return &SearchNearTextParams{
		Context: ctx,
	}
}

// NewSearchNearTextParamsWithHTTPClient creates a new SearchNearTextParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchNearTextParamsWithHTTPClient(client *http.Client) *SearchNearTextParams {
	return &SearchNearTextParams{
		HTTPClient: client,
	}
}

/*
SearchNearTextParams contains all the parameters to send to the API endpoint

	for the search near text operation.

	Typically these are written to a http.Request.
*/
type SearchNearTextParams struct {

	/* Body.

	   The near-text search request.
	*/
	Body *models.SearchNearTextRequest

	/* Collection.

	   The name (or alias) of the collection to search. A lowercase first letter is normalized to the canonical uppercase form.
	*/
	Collection string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search near text params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchNearTextParams) WithDefaults() *SearchNearTextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search near text params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchNearTextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search near text params
func (o *SearchNearTextParams) WithTimeout(timeout time.Duration) *SearchNearTextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search near text params
func (o *SearchNearTextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search near text params
func (o *SearchNearTextParams) WithContext(ctx context.Context) *SearchNearTextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search near text params
func (o *SearchNearTextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search near text params
func (o *SearchNearTextParams) WithHTTPClient(client *http.Client) *SearchNearTextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search near text params
func (o *SearchNearTextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search near text params
func (o *SearchNearTextParams) WithBody(body *models.SearchNearTextRequest) *SearchNearTextParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search near text params
func (o *SearchNearTextParams) SetBody(body *models.SearchNearTextRequest) {
	o.Body = body
}

// WithCollection adds the collection to the search near text params
func (o *SearchNearTextParams) WithCollection(collection string) *SearchNearTextParams {
	o.SetCollection(collection)
	return o
}

// SetCollection adds the collection to the search near text params
func (o *SearchNearTextParams) SetCollection(collection string) {
	o.Collection = collection
}

// WriteToRequest writes these params to a swagger request
func (o *SearchNearTextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param collection
	if err := r.SetPathParam("collection", o.Collection); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
