name: Assign Label non-members for issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the user is a member and assign label to non-members
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner
            const repo = context.repo.repo
            const isIssue = context.payload.issue
            const isPR = context.payload.pull_request            

            if (isIssue) {
              issue_number = context.payload.issue.number
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['notify']
              })
            } else if (isPR) {
              userLogin = context.payload.pull_request.user.login
              issue_number = context.payload.pull_request.number
                   
              const isMember = await github.rest.repos.listCollaborators({
                owner,
                repo
              }).some(collaborator => collaborator.login === userLogin)
              
              if (!isMember) {              
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number,
                  labels: ['notify','community']
                })
              }
            }
