name: golangci-lint
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Run golangci-lint
        uses: ./.github/actions/golangci-lint
  protolint:
    name: protolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: yoheimuta/action-protolint@e62319541dc5107df5e3a5010acb8987004d3d25 # v1
  python:
    name: python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # stable
        with:
          version: "26.3.1"
  custom:
    name: custom checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Error groups checks
        run: ./tools/linter_error_groups.sh
      - name: goroutine checks
        run: ./tools/linter_go_routines.sh
      - name: waitgroups checks
        run: ./tools/linter_waitgroups_done.sh