name: Unit and integration tests

on: [push, fork, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Unit and integration test
        run: ./test/run.sh --unit-and-integration-only
